import {
  closeSync, constants, fstatSync, ftruncateSync, lstatSync, openSync, readFileSync, writeFileSync,
} from 'node:fs';
import { fileURLToPath } from 'node:url';
import ts from 'typescript';

const LIVE_SOURCE_URL = new URL('../../packages/core/src/spec.ts', import.meta.url);
const CATALOG_URL = new URL('./catalog.json', import.meta.url);
const GENERATED_KERN_URL = new URL('../../examples/kern-frontend/builtin-node-types.generated.kern', import.meta.url);
const FORMAT = 'kern.frontend.builtin-node-types.1';
const SOURCE_PATH = 'packages/core/src/spec.ts';

function fail(detail) {
  throw new TypeError(`frontend builtin-node catalog rejection: ${detail}`);
}

function readRegular(url, label) {
  const path = fileURLToPath(url);
  const stat = lstatSync(path);
  if (!stat.isFile() || stat.isSymbolicLink()) fail(`${label} must be a regular file`);
  const bytes = readFileSync(path);
  if (bytes.includes(13)) fail(`${label} must use LF line endings`);
  return bytes;
}

function unwrap(node) {
  if (ts.isAsExpression(node) || ts.isSatisfiesExpression(node) || ts.isParenthesizedExpression(node)) {
    return unwrap(node.expression);
  }
  return node;
}

function constAsserted(node) {
  if (ts.isParenthesizedExpression(node) || ts.isSatisfiesExpression(node)) return constAsserted(node.expression);
  return ts.isAsExpression(node) && ts.isTypeReferenceNode(node.type) &&
    ts.isIdentifier(node.type.typeName) && node.type.typeName.text === 'const';
}

export function extractBuiltinNodeTypes(source, sourcePath = SOURCE_PATH) {
  const file = ts.createSourceFile(sourcePath, source, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS);
  if (file.parseDiagnostics.length !== 0) fail('live source must parse');
  const matches = [];
  for (const statement of file.statements) {
    if (!ts.isVariableStatement(statement)) continue;
    for (const declaration of statement.declarationList.declarations) {
      if (ts.isIdentifier(declaration.name) && declaration.name.text === 'NODE_TYPES') matches.push(declaration);
    }
  }
  if (matches.length !== 1) fail('live source must contain exactly one top-level NODE_TYPES');
  const declaration = matches[0];
  const declarationStatement = declaration.parent.parent;
  if (!(declarationStatement.declarationList.flags & ts.NodeFlags.Const)) {
    fail('NODE_TYPES must remain a const declaration');
  }
  if (!declaration.initializer || !constAsserted(declaration.initializer)) fail('NODE_TYPES must retain its const assertion');
  const initializer = unwrap(declaration.initializer);
  if (!ts.isArrayLiteralExpression(initializer)) fail('NODE_TYPES must remain a static array literal');
  const values = initializer.elements.map((element, index) => {
    if (!ts.isStringLiteral(element)) fail(`NODE_TYPES[${index}] must remain a string literal`);
    return element.text;
  });
  if (values.length === 0 || new Set(values).size !== values.length) fail('NODE_TYPES must be non-empty and unique');
  return values;
}

function expectedCatalog(nodeTypes) {
  return { constant: 'NODE_TYPES', format: FORMAT, nodeTypes, sourcePath: SOURCE_PATH };
}

export function renderBuiltinNodeCatalog(nodeTypes) {
  return `${JSON.stringify(expectedCatalog(nodeTypes), null, 2)}\n`;
}

export function renderBuiltinNodeKern(nodeTypes) {
  const lines = [
    '# Generated by scripts/kern-frontend-builtin-node-type-attestation/catalog.mjs. Do not edit.',
    'fn name=builtinnodetypes returns="string[]"',
    '  handler lang="kern"',
    '    let name=values value="[]"',
  ];
  for (const value of nodeTypes) {
    const literal = JSON.stringify(value).replaceAll('\\', '\\\\').replaceAll('"', '\\"');
    lines.push(`    do value="values.push(${literal})"`);
  }
  lines.push('    return value="values"', '');
  return lines.join('\n');
}

export function validateBuiltinNodeCatalog(catalogBytes, kernBytes, liveSourceBytes) {
  const nodeTypes = extractBuiltinNodeTypes(liveSourceBytes.toString('utf8'));
  const expectedJson = renderBuiltinNodeCatalog(nodeTypes);
  const expectedKern = renderBuiltinNodeKern(nodeTypes);
  if (catalogBytes.toString('utf8') !== expectedJson) fail('catalog bytes drifted from live NODE_TYPES');
  if (kernBytes.toString('utf8') !== expectedKern) fail('generated KERN bytes drifted from live NODE_TYPES');
  return Object.freeze([...nodeTypes]);
}

export function loadBuiltinNodeCatalog() {
  return validateBuiltinNodeCatalog(
    readRegular(CATALOG_URL, 'catalog'),
    readRegular(GENERATED_KERN_URL, 'generated KERN catalog'),
    readRegular(LIVE_SOURCE_URL, 'live NODE_TYPES source'),
  );
}

function openRegularOutput(url, label) {
  const path = fileURLToPath(url);
  const stat = lstatSync(path);
  if (!stat.isFile() || stat.isSymbolicLink()) fail(`${label} must be a pre-existing regular file`);
  const descriptor = openSync(path, constants.O_WRONLY | constants.O_NOFOLLOW);
  if (!fstatSync(descriptor).isFile()) {
    closeSync(descriptor);
    fail(`${label} must remain a regular file`);
  }
  return descriptor;
}

export function writeBuiltinNodeCatalogFiles(catalogUrl, generatedKernUrl, nodeTypes) {
  let catalogDescriptor;
  let kernDescriptor;
  try {
    catalogDescriptor = openRegularOutput(catalogUrl, 'catalog output');
    kernDescriptor = openRegularOutput(generatedKernUrl, 'generated KERN output');
    ftruncateSync(catalogDescriptor, 0);
    ftruncateSync(kernDescriptor, 0);
    writeFileSync(catalogDescriptor, renderBuiltinNodeCatalog(nodeTypes));
    writeFileSync(kernDescriptor, renderBuiltinNodeKern(nodeTypes));
  } finally {
    if (kernDescriptor !== undefined) closeSync(kernDescriptor);
    if (catalogDescriptor !== undefined) closeSync(catalogDescriptor);
  }
}

export function writeBuiltinNodeCatalog() {
  const nodeTypes = extractBuiltinNodeTypes(readRegular(LIVE_SOURCE_URL, 'live NODE_TYPES source').toString('utf8'));
  writeBuiltinNodeCatalogFiles(CATALOG_URL, GENERATED_KERN_URL, nodeTypes);
  return nodeTypes.length;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === fileURLToPath(new URL(`file://${process.argv[1]}`))) {
  if (process.argv.length === 3 && process.argv[2] === '--write') {
    console.log(`wrote ${writeBuiltinNodeCatalog()} built-in node types`);
  } else if (process.argv.length === 2) {
    console.log(`built-in node catalog: ${loadBuiltinNodeCatalog().length} exact entries`);
  } else {
    fail('usage: catalog.mjs [--write]');
  }
}
