export const KERN_PAIR_HELPERS_PY = [
  'def _kern_pairs(__k_v):',
  '    return __k_v.items() if hasattr(__k_v, "items") else iter(__k_v)',
  '',
  'async def _kern_async_pairs(__k_v):',
  '    if hasattr(__k_v, "__aiter__"):',
  '        async for __k_item in __k_v:',
  '            yield __k_item',
  '    else:',
  '        for __k_item in _kern_pairs(__k_v):',
  '            yield __k_item',
].join('\n');

export const KERN_FMT_HELPER_PY = [
  'try:',
  '    _KERN_UNDEFINED',
  'except NameError:',
  '    class _KernUndefined:',
  // JS `undefined` is falsy: `!undefined`, `undefined ? a : b`, `if (undefined)`,
  // and `undefined || x` must behave as falsy. A bare object is truthy in Python,
  // so override __bool__ — without this the sentinel diverges from JS in every
  // truthiness position. Identity (`is`) is unaffected, so the `??` checks hold.
  '        def __bool__(self): return False',
  "        def __repr__(self): return 'undefined'",
  "        def __str__(self): return 'undefined'",
  '    _KERN_UNDEFINED = _KernUndefined()',
  '',
  'def _kern_fmt(__k_v):',
  '    if __k_v is _KERN_UNDEFINED:',
  "        return 'undefined'",
  '    if __k_v is None:',
  "        return 'null'",
  '    if isinstance(__k_v, bool):',
  "        return 'true' if __k_v else 'false'",
  '    if isinstance(__k_v, str):',
  '        return __k_v',
  '    if isinstance(__k_v, float) and __k_v != __k_v:',
  "        return 'NaN'",
  // JS String(Infinity) is "Infinity"/"-Infinity"; Python str(inf) is "inf".
  // Check before is_integer() — inf.is_integer() is False and int(inf) raises.
  "    if isinstance(__k_v, float) and __k_v == float('inf'):",
  "        return 'Infinity'",
  "    if isinstance(__k_v, float) and __k_v == float('-inf'):",
  "        return '-Infinity'",
  '    if isinstance(__k_v, float) and __k_v.is_integer():',
  '        return str(int(__k_v))',
  '    if isinstance(__k_v, (int, float)):',
  '        return str(__k_v)',
  '    if isinstance(__k_v, (list, tuple)):',
  "        return ','.join(",
  "            '' if x is None or x is _KERN_UNDEFINED else _kern_fmt(x)",
  '            for x in __k_v',
  '        )',
  '    if isinstance(__k_v, dict):',
  "        return '[object Object]'",
  '    return str(__k_v)',
  '',
  'def __kern_add(left, right):',
  '    # JS `+`: string concat when either operand is string-ish (ToPrimitive →',
  '    # string for str/array/object/tuple); otherwise numeric addition with ToNumber',
  '    # coercion (null→0, undefined→NaN, bool→0/1) so `5 + null` is 5, not "5null".',
  '    if isinstance(left, (str, list, tuple, dict)) or isinstance(right, (str, list, tuple, dict)):',
  '        return _kern_fmt(left) + _kern_fmt(right)',
  '    def _num(v):',
  '        if v is _KERN_UNDEFINED:',
  "            return float('nan')",
  '        if v is None:',
  '            return 0',
  '        if isinstance(v, bool):',
  '            return 1 if v else 0',
  '        return v',
  '    # ToNumber path for the KERN value domain (numbers/bool/null/undefined).',
  '    # Any exotic host type (set, custom object) that escapes the string-ish',
  '    # check falls back to JS object→string concat rather than raising.',
  '    try:',
  '        return _num(left) + _num(right)',
  '    except TypeError:',
  '        return _kern_fmt(left) + _kern_fmt(right)',
].join('\n');

export const KERN_I32_HELPER_PY = [
  'import math',
  'def _i32(x):',
  '    if x is None: return 0',
  '    try:',
  '        if not math.isfinite(x): return 0',
  '        val = int(math.trunc(x))',
  '    except Exception:',
  '        try:',
  '            val = float(x)',
  '            if not math.isfinite(val): return 0',
  '            val = int(math.trunc(val))',
  '        except Exception:',
  '            return 0',
  '    return ((val & 0xFFFFFFFF) ^ 0x80000000) - 0x80000000',
].join('\n');

export const KERN_TMOD_HELPER_PY = [
  'import math',
  'def _tmod(a, b):',
  '    if a is None: a = 0',
  '    if b is None: b = 0',
  '    try:',
  '        fa = float(a)',
  '        fb = float(b)',
  '    except Exception:',
  "        return float('nan')",
  "    if math.isnan(fa) or math.isnan(fb): return float('nan')",
  "    if math.isinf(fa): return float('nan')",
  "    if fb == 0: return float('nan')",
  '    if math.isinf(fb): return fa',
  '    return fa - math.trunc(fa / fb) * fb',
].join('\n');

export const KERN_JS_HELPER_PY = [
  // Slice S4 — ToBoolean / KERN truthiness substrate. `js_truthy` is an EXPLICIT
  // falsy-set predicate over the KERN value domain: falsy iff x is the undefined
  // sentinel, None, a boolean False, numeric zero (+0/-0.0/0j), NaN, or "".
  // Everything else is truthy — INCLUDING [], {}, callables, class instances, and
  // user objects whose Python __bool__/__len__ are falsy. It NEVER delegates to
  // bool(x), len(x), x.__bool__(), x.__len__(), or a ToNumber string conversion:
  // "0", "false", " " are all truthy; only "" is falsy. `bool` is checked BEFORE
  // the numeric branch because Python `bool` subclasses `int`. The undefined
  // sentinel is matched by IDENTITY (`is _KERN_UNDEFINED`) — its __bool__ = False
  // override is for bare-truthiness positions only and must NOT be generalized to
  // user objects. `_kern_truthy` is the canonical name; `js_truthy` is the alias
  // the existing array-predicate lowerings (filter/some/every/find-family) call.
  'try:',
  '    _KERN_UNDEFINED',
  'except NameError:',
  '    class _KernUndefined:',
  '        def __bool__(self): return False',
  "        def __repr__(self): return 'undefined'",
  "        def __str__(self): return 'undefined'",
  '    _KERN_UNDEFINED = _KernUndefined()',
  'def _kern_truthy(x):',
  '    if x is _KERN_UNDEFINED or x is None or x is False: return False',
  '    if isinstance(x, bool): return x',
  // `x == x` is False only for NaN, so `x != 0 and x == x` rejects both numeric
  // zero (incl. -0.0 and 0j) and NaN without delegating to math.isnan / bool().
  '    if isinstance(x, (int, float, complex)): return x != 0 and x == x',
  '    if isinstance(x, str): return len(x) > 0',
  '    return True',
  'def js_truthy(x):',
  '    return _kern_truthy(x)',
  'def js_equals(a, b):',
  '    return a == b',
].join('\n');

export const KERN_JS_ARRAY_HELPERS_PY = [
  '_KERN_JS_FILL_ABSENT = object()',
  '',
  'try:',
  '    _KERN_UNDEFINED',
  'except NameError:',
  '    class _KernUndefined:',
  '        def __bool__(self): return False',
  "        def __repr__(self): return 'undefined'",
  "        def __str__(self): return 'undefined'",
  '    _KERN_UNDEFINED = _KernUndefined()',
  '',
  'def _kern_js_is_undefined(__k_x):',
  '    return __k_x is _KERN_UNDEFINED',
  '',
  'def _kern_js_to_integer_or_infinity(__k_x):',
  '    if __k_x is None:',
  '        return 0',
  '    if _kern_js_is_undefined(__k_x):',
  '        return 0',
  '    try:',
  '        __k_n = float(__k_x)',
  '    except Exception:',
  '        return 0',
  '    if __k_n != __k_n:',
  '        return 0',
  '    if __k_n == float("inf"):',
  '        return float("inf")',
  '    if __k_n == float("-inf"):',
  '        return float("-inf")',
  '    return int(__k_n)',
  '',
  'def _kern_js_relative_index(__k_index, __k_len):',
  '    if __k_index == float("-inf"):',
  '        return 0',
  '    if __k_index == float("inf"):',
  '        return __k_len',
  '    if __k_index < 0:',
  '        return max(__k_len + __k_index, 0)',
  '    return min(__k_index, __k_len)',
  '',
  'def _kern_js_fill(__k_list, __k_value, __k_start=0, __k_end=_KERN_JS_FILL_ABSENT):',
  '    __k_len = len(__k_list)',
  '    __k_s = _kern_js_relative_index(_kern_js_to_integer_or_infinity(__k_start), __k_len)',
  '    if __k_end is _KERN_JS_FILL_ABSENT or _kern_js_is_undefined(__k_end):',
  '        __k_e = __k_len',
  '    else:',
  '        __k_e = _kern_js_relative_index(_kern_js_to_integer_or_infinity(__k_end), __k_len)',
  '    __k_list[__k_s:__k_e] = [__k_value] * max(0, __k_e - __k_s)',
  '    return __k_list',
].join('\n');

export const KERN_JS_OBJECT_HELPERS_PY = [
  'def _kern_js_is_array_index(__k_key):',
  '    __k_s = str(__k_key)',
  '    if not __k_s.isdigit(): return False',
  '    if len(__k_s) > 1 and __k_s[0] == "0": return False',
  '    __k_n = int(__k_s)',
  '    return 0 <= __k_n < 4294967295 and __k_s == str(__k_n)',
  '',
  'def _kern_js_property_items(__k_obj):',
  '    if __k_obj is None:',
  '        raise TypeError("Cannot convert undefined or null to object")',
  '    if hasattr(__k_obj, "items"):',
  '        __k_raw = list(__k_obj.items())',
  '    else:',
  '        try:',
  '            __k_raw = [(str(__k_i), __k_v) for __k_i, __k_v in enumerate(__k_obj)]',
  '        except TypeError:',
  '            __k_raw = []',
  '    __k_indexed = []',
  '    __k_rest = []',
  '    for __k_pos, (__k_key, __k_val) in enumerate(__k_raw):',
  '        __k_s = str(__k_key)',
  '        if _kern_js_is_array_index(__k_s):',
  '            __k_indexed.append((int(__k_s), __k_s, __k_val))',
  '        else:',
  '            __k_rest.append((__k_pos, __k_s, __k_val))',
  '    return [(__k_s, __k_v) for _, __k_s, __k_v in sorted(__k_indexed, key=lambda __k_item: __k_item[0])] + [(__k_s, __k_v) for _, __k_s, __k_v in __k_rest]',
  '',
  'def _kern_js_object_keys(__k_obj):',
  '    return [__k_k for __k_k, _ in _kern_js_property_items(__k_obj)]',
  '',
  'def _kern_js_object_values(__k_obj):',
  '    return [__k_v for _, __k_v in _kern_js_property_items(__k_obj)]',
  '',
  'def _kern_js_object_entries(__k_obj):',
  '    return [[__k_k, __k_v] for __k_k, __k_v in _kern_js_property_items(__k_obj)]',
].join('\n');

export const KERN_JS_STRING_HELPERS_PY = [
  'def _kern_js_split_limit(__k_limit):',
  '    if __k_limit is None:',
  '        return None',
  '    try:',
  '        __k_n = float(__k_limit)',
  '    except Exception:',
  '        return 0',
  '    if __k_n != __k_n or __k_n in (float("inf"), float("-inf")):',
  '        return 0',
  '    return int(__k_n) % 4294967296',
  '',
  'def _kern_js_replacement(__k_repl, __k_match, __k_prefix, __k_suffix):',
  '    __k_repl = str(__k_repl)',
  '    __k_out = []',
  '    __k_i = 0',
  '    while __k_i < len(__k_repl):',
  '        __k_c = __k_repl[__k_i]',
  '        if __k_c == "$" and __k_i + 1 < len(__k_repl):',
  '            __k_n = __k_repl[__k_i + 1]',
  '            if __k_n == "$":',
  '                __k_out.append("$"); __k_i += 2; continue',
  '            if __k_n == "&":',
  '                __k_out.append(__k_match); __k_i += 2; continue',
  '            if __k_n == "`":',
  '                __k_out.append(__k_prefix); __k_i += 2; continue',
  '            if __k_n == "\'":',
  '                __k_out.append(__k_suffix); __k_i += 2; continue',
  '        __k_out.append(__k_c)',
  '        __k_i += 1',
  '    return "".join(__k_out)',
  '',
  'def _kern_js_replace(__k_s, __k_search, __k_repl, __k_all=False):',
  '    __k_s = str(__k_s)',
  '    __k_search = str(__k_search)',
  '    if not __k_all:',
  '        __k_idx = __k_s.find(__k_search)',
  '        if __k_idx < 0: return __k_s',
  '        __k_end = __k_idx + len(__k_search)',
  '        return __k_s[:__k_idx] + _kern_js_replacement(__k_repl, __k_search, __k_s[:__k_idx], __k_s[__k_end:]) + __k_s[__k_end:]',
  '    if __k_search == "":',
  '        return "".join(_kern_js_replacement(__k_repl, "", __k_s[:__k_i], __k_s[__k_i:]) + (__k_s[__k_i] if __k_i < len(__k_s) else "") for __k_i in range(len(__k_s) + 1))',
  '    __k_parts = []',
  '    __k_pos = 0',
  '    while True:',
  '        __k_idx = __k_s.find(__k_search, __k_pos)',
  '        if __k_idx < 0:',
  '            __k_parts.append(__k_s[__k_pos:])',
  '            break',
  '        __k_end = __k_idx + len(__k_search)',
  '        __k_parts.append(__k_s[__k_pos:__k_idx])',
  '        __k_parts.append(_kern_js_replacement(__k_repl, __k_search, __k_s[:__k_idx], __k_s[__k_end:]))',
  '        __k_pos = __k_end',
  '    return "".join(__k_parts)',
].join('\n');
