export const GENERIC_PROPERTY_THEME_REFS_FIXTURES = Object.freeze([
  { id: 'zero-themes', source: 'screen a=one b="two"' },
  { id: 'one-theme', source: 'screen $base' },
  { id: 'ordered-themes', source: 'screen $base $accent' },
  { id: 'duplicate-themes', source: 'screen $base $accent $base' },
  { id: 'properties-around-theme', source: 'screen a=one $base b=two' },
  { id: 'bare-adjacent-theme', source: 'screen a=bare$base' },
  { id: 'empty-before-theme', source: 'screen a=$base b=two' },
  { id: 'theme-between-duplicates', source: 'screen a="one" $base b=two a=three' },
  { id: 'astral-duplicate-after-theme', source: 'screen a="😀" $base b=one a=two' },
  { id: 'hyphen-underscore-theme', source: 'screen $base-dark $_accent2' },
  { id: 'quoted-theme-like-text', source: 'screen a="$base $accent"' },
  { id: 'expression-theme-like-text', source: 'screen a={{ "$base" }}' },
  { id: 'unknown-node-theme', source: 'm4166_unknown $base a=one' },
  { id: 'inline-comment-theme-like', source: 'screen $base a=one # $ignored' },
  { id: 'dropped-node', source: '123 $base a=one' },
  { id: 'style-only-deferred', source: 'screen {bg:red}' },
  { id: 'style-before-theme-deferred', source: 'screen {bg:red} $base' },
  { id: 'style-value-deferred', source: 'screen a={bg:red}' },
  { id: 'style-bare-deferred', source: 'screen a=one{bg:red}' },
  { id: 'unexpected-before-theme-deferred', source: 'screen ) $base' },
  { id: 'missing-equals-before-theme-deferred', source: 'screen bare $base' },
  { id: 'property-limit-before-style', source: 'screen a0=0 a1=1 a2=2 a3=3 a4=4 a5=5 a6=6 a7=7 a8=8 {bg:red}' },
  { id: 'theme-limit-before-style', source: 'screen $t0 $t1 $t2 $t3 $t4 $t5 $t6 $t7 $t8 {bg:red}' },
  { id: 'terminal-whitespace', source: 'screen a=one   ' },
]);
