export const GENERIC_PROPERTY_ADMISSION_FIXTURES = Object.freeze([
  { id: 'none-at-eof', source: 'screen' },
  { id: 'none-style-first', source: 'screen {p:1} name=Home' },
  { id: 'none-nonadjacent-equals', source: 'screen name =Home' },
  { id: 'empty-at-eof', source: 'screen title=' },
  { id: 'empty-before-whitespace', source: 'screen title= value' },
  { id: 'quoted', source: 'screen title="hello world"' },
  { id: 'quoted-empty', source: 'screen title=""' },
  { id: 'quoted-escape', source: 'screen title="hello \\"world\\""' },
  { id: 'expression', source: 'screen value={{ x + 1 }}' },
  { id: 'nested-expression', source: 'screen value={{ outer({{ inner }}) }}' },
  { id: 'unclosed-expression', source: 'screen value={{ broken' },
  { id: 'bare-single', source: 'screen name=Home' },
  { id: 'bare-multiple-token-kinds', source: 'screen path=/api/v1,2' },
  { id: 'bare-unknown-at', source: 'screen target=wide@mobile' },
  { id: 'style-zero-token-boundary', source: 'screen title={p:1}' },
  { id: 'theme-zero-token-boundary', source: 'screen title=$brand' },
  { id: 'leading-property-whitespace', source: 'screen\t  name=Home' },
  { id: 'second-property-deferred', source: 'screen name=Home target=ink' },
  { id: 'inline-comment-retained-boundary', source: 'screen name=Home # payload=ignored' },
  { id: 'unknown-node-property', source: 'm4164_unknown name=Home' },
  { id: 'dropped-node', source: '123 name=Home' },
]);
