import type { GeneratedArtifact, IRNode, ResolvedKernConfig } from '@kernlang/core';
import { generateCoreNode, getChildren, mapSemanticType, propsOf } from '@kernlang/core';
import type { CoreArtifactRef } from './express-types.js';
import { slugify } from './express-utils.js';

// ── Core node artifact mapping ────────────────────────────────────────────

/** Map core node type → output directory + artifact type. */
export function coreNodeMeta(type: string): { dir: string; artifactType: GeneratedArtifact['type'] } {
  switch (type) {
    case 'interface': return { dir: 'models', artifactType: 'model' };
    case 'model':     return { dir: 'models', artifactType: 'model' };
    case 'repository':return { dir: 'models', artifactType: 'repository' };
    case 'cache':     return { dir: 'lib', artifactType: 'lib' };
    case 'dependency':return { dir: 'lib', artifactType: 'lib' };
    case 'service':   return { dir: 'services', artifactType: 'service' };
    case 'type':      return { dir: 'types', artifactType: 'types' };
    case 'config':    return { dir: 'config', artifactType: 'config' };
    case 'error':     return { dir: 'errors', artifactType: 'error' };
    default:          return { dir: 'lib', artifactType: 'lib' };
  }
}

export const TOP_LEVEL_CORE = new Set([
  'type', 'interface', 'service', 'fn', 'machine', 'error',
  'module', 'config', 'store', 'event', 'const',
  // Data layer
  'model', 'repository', 'cache', 'dependency',
  // Backend infrastructure
  'job', 'storage', 'email',
]);

// ── Prisma Schema Artifact ───────────────────────────────────────────────

/** Map KERN column type to Prisma schema type. Strips @db.* decorators for non-PostgreSQL providers. */
export function mapColumnToPrisma(kernType: string, provider: string): string {
  const mapped = mapSemanticType(kernType, 'prisma');
  if (provider !== 'postgresql') {
    return mapped.replace(/ @db\.\w+/g, '');
  }
  return mapped;
}

/**
 * Build a complete schema.prisma file from model IR nodes.
 * This runs ONLY in Express — not in the shared codegen path.
 */
export function formatPrismaDefault(value: string): string {
  const trimmed = value.trim();
  if (/^-?\d+(?:\.\d+)?$/.test(trimmed)) return trimmed;
  if (trimmed === 'true' || trimmed === 'false') return trimmed;
  if (trimmed === 'uuid4()' || trimmed === 'uuid4') return 'uuid()';
  if (trimmed === 'now()' || trimmed === 'now') return 'now()';
  if (trimmed === 'autoincrement()' || trimmed === 'autoincrement') return 'autoincrement()';
  if (/^[A-Za-z_]\w*\([^)]*\)$/.test(trimmed)) return trimmed;
  return `"${trimmed}"`;
}

export function buildPrismaArtifact(modelNodes: IRNode[], config?: ResolvedKernConfig): GeneratedArtifact | null {
  if (modelNodes.length === 0) return null;

  const provider = config?.express?.prisma?.provider ?? 'postgresql';

  const lines: string[] = [
    '// Generated by KERN. Run migrations:',
    '//   npx prisma generate',
    '//   npx prisma migrate dev --name init',
    '//   npx prisma db push  (for prototyping)',
    '',
    'generator client {',
    '  provider = "prisma-client-js"',
    '}',
    '',
    'datasource db {',
    `  provider = "${provider}"`,
    '  url      = env("DATABASE_URL")',
    '}',
    '',
  ];

  for (const node of modelNodes) {
    const props = propsOf<'model'>(node);
    const name = props.name || 'UnknownModel';
    const table = props.table;
    const columns = getChildren(node, 'column');
    const relations = getChildren(node, 'relation');

    lines.push(`model ${name} {`);

    for (const col of columns) {
      const cp = propsOf<'column'>(col);
      const colName = cp.name || 'column';
      const rawType = mapColumnToPrisma(cp.type || 'String', provider);
      // Split off Prisma decorators embedded in the type (e.g., 'String @db.Uuid')
      const [prismaType, ...typeDecorators] = rawType.split(' ');
      const decorators: string[] = [...typeDecorators];
      const isPrimary = cp.primary === 'true' || cp.primary === true;
      const isUnique = cp.unique === 'true' || cp.unique === true;
      const isNullable = cp.nullable === 'true' || cp.nullable === true;
      const defaultVal = cp.default;

      if (isPrimary) decorators.push('@id');
      if (isUnique) decorators.push('@unique');
      if (defaultVal !== undefined) decorators.push(`@default(${formatPrismaDefault(defaultVal)})`);

      const nullMark = isNullable ? '?' : '';
      const decoStr = decorators.length > 0 ? ' ' + decorators.join(' ') : '';
      lines.push(`  ${colName} ${prismaType}${nullMark}${decoStr}`);
    }

    for (const rel of relations) {
      const rp = propsOf<'relation'>(rel);
      const relName = rp.name || 'relation';
      const target = rp.target || rp.model || 'Unknown';
      const kind = rp.kind || 'one-to-many';
      const fk = rp.foreignKey;

      if (kind === 'one-to-many' || kind === 'many-to-many') {
        lines.push(`  ${relName} ${target}[]`);
      } else {
        const relDeco = fk ? ` @relation(fields: [${fk}], references: [id])` : '';
        lines.push(`  ${relName} ${target}?${relDeco}`);
      }
    }

    if (table) {
      lines.push('');
      lines.push(`  @@map("${table}")`);
    }

    lines.push('}');
    lines.push('');
  }

  return { path: 'prisma/schema.prisma', content: lines.join('\n'), type: 'prisma' };
}

export function buildCoreArtifact(node: IRNode): CoreArtifactRef {
  const name = String((node.props || {}).name || node.type);
  const fileBase = slugify(name);
  const { dir, artifactType } = coreNodeMeta(node.type);
  const tsLines = generateCoreNode(node);
  const content = tsLines.join('\n');

  // Extract export names for the import line
  const exportNames: string[] = [];
  for (const line of tsLines) {
    const m = line.match(/^export (?:type |interface |function |const |class |enum |abstract class )(\w+)/);
    if (m) exportNames.push(m[1]);
  }

  return {
    importPath: `./${dir}/${fileBase}.js`,
    exportNames,
    artifact: {
      path: `${dir}/${fileBase}.ts`,
      content,
      type: artifactType,
    },
  };
}
