// Facade. Source of truth: packages/core/src/kern/utils/external-boundary-utils.kern.
export type {
  ExternalBoundaryInheritance,
  ExternalBoundaryIslandShape,
  ExternalBoundaryRuntimeShape,
  ExternalBoundaryShape,
  ExternalCapabilityIslandShape,
  ExternalLoosePythonSidecarNameShape,
  ExternalRuntimeImportShape,
  ExternalSidecarBoundaryShape,
  ExternalSidecarIslandShape,
  ExternalSidecarManifestShape,
  ExternalSidecarPackageShape,
  ExternalBoundaryStringKey,
} from './generated/utils/external-boundary-utils.js';

export {
  externalBoundaryFromParts,
  externalBoundaryFromExternParts,
  externalBoundaryFromImportParts,
  externalBoolProp,
  externalCapabilityIslandFromParts,
  externalImportBindingFromParts,
  externalIslandRefFromParts,
  externalPackageNameFromExternProps,
  externalPackageNameFromImportProps,
  externalRuntimeImports,
  externalLooseSidecarManifestFromBoundary,
  externalLoosePythonSidecarName,
  externalSidecarManifestFromIsland,
  externalSidecarPackageFromBoundary,
  externalSidecarPackageKey,
  externalStringProp,
  hasExternalRuntimeImports,
  hasExplicitExternalPackageProp,
  inheritExternalArgs,
  inheritExternalString,
  isLoosePythonBoundaryShape,
  isPythonSidecarBoundaryShape,
  mergeExternalSidecarManifestPackage,
  mergeExternalEffects,
  splitExternalNames,
} from './generated/utils/external-boundary-utils.js';
