export const LEXICAL_FIXTURES = [
  { id: 'empty', source: '' },
  { id: 'neutral', source: 'screen\n  text' },
  { id: 'eligible-hash', source: 'text value=ok  # payload with " {{ \\' },
  { id: 'eligible-slashes', source: 'text value=ok\t// payload with \' }} \\' },
  { id: 'full-line-comment-boundary', source: '# full line boundary\nscreen' },
  { id: 'hash-inside-double', source: 'text value="hello # world"' },
  { id: 'slashes-inside-single', source: "text value='url // path'" },
  { id: 'markers-inside-expression', source: 'text value={{ value # still expression // still expression }}' },
  { id: 'markers-inside-style', source: 'text { color: #fff, url: //asset }' },
  { id: 'non-space-tab-whitespace-marker', source: 'text\u000b#not-a-marker\ntext\u000c//not-a-marker' },
  { id: 'nested-expression-adjacency', source: 'text value={{{{ inner }}}}' },
  { id: 'nested-style', source: 'text { outer: { inner: 1 } }' },
  { id: 'quotes-inside-style', source: "text { value: 'a } # //', other: \"b }\" }" },
  { id: 'astral-before-marker', source: 'text value="😀"  # note' },
  { id: 'multiline-double', source: 'text value="one\ntwo"  # done' },
  { id: 'multiline-expression', source: 'text value={{\n  inner({{ value }})\n}} // done' },
  { id: 'escape-before-inserted-lf', source: 'text value="one\\\ntwo"' },
  { id: 'even-backslashes', source: 'text value="two\\\\"' },
  { id: 'final-lf', source: 'screen\n' },
  { id: 'eof-unclosed-excluded', source: 'text value="open\nstill open' },
];
