export const GENERIC_PROPERTY_LOOP_FIXTURES = Object.freeze([
  { id: 'zero-properties', source: 'screen' },
  { id: 'one-bare', source: 'screen name=Home' },
  { id: 'two-distinct', source: 'screen name=Home target=ink' },
  { id: 'empty-and-quoted-empty', source: 'screen empty= quoted=""' },
  { id: 'expression-and-bare', source: 'screen value={{ x + 1 }} path=/api/v1,2' },
  { id: 'duplicate-last-write', source: 'screen a=one b=two a=three' },
  { id: 'quoted-repeat-keeps-order', source: 'screen a="one" b="two" a="three"' },
  { id: 'quoted-delete', source: 'screen a="one" b="two" a=three' },
  { id: 'quoted-delete-readd', source: 'screen a="one" b="two" a=three a="four"' },
  { id: 'expression-deletes-quote', source: 'screen a="one" a={{ two }}' },
  { id: 'empty-deletes-quote', source: 'screen a="one" a=' },
  { id: 'three-duplicate-coordinates', source: 'screen a="one" b=two a=three c="four" b="five" a="six"' },
  { id: 'unknown-node-loop', source: 'm4165_unknown a=one a="two"' },
  { id: 'inline-hash-comment', source: 'screen a=one b="two" # constructor=ignored' },
  { id: 'inline-slash-comment', source: 'screen a="// constructor=quoted" b=two // toString=ignored' },
  { id: 'dropped-node', source: '123 name=Home' },
  { id: 'inherited-name-in-bare-value', source: 'screen safe=toString=value' },
  { id: 'astral-before-duplicate', source: 'screen a="😀" b=one a=two' },
]);
