export const KEYWORD_HANDLER_CATALOG = Object.freeze([
  'fn', 'let', 'return', 'throw', 'do', 'if', 'while', 'doc', 'theme', 'import', 'island', 'route', 'params',
  'auth', 'validate', 'error', 'derive', 'guard', 'effect', 'strategy', 'trigger', 'respond', 'expect', 'rule',
  'message', 'middleware',
]);

// These expectations are independently authored from the verified handler
// contract. They are never generated by importing or executing the bootstrap
// KEYWORD_HANDLERS map.
export const KEYWORD_HANDLER_FIXTURES = Object.freeze([
  {
    id: 'fn-first-class', type: 'fn', source: 'fn greet(name: string): Result<string> async=true',
    expectedHandlerProps: {
      name: 'greet', params: 'name:string', returns: 'Result<string>', async: true, __firstClassSyntax: true,
    },
    cursorDecision: 'commit-all',
  },
  {
    id: 'let-first-class', type: 'let', source: 'let total: number = left + right',
    expectedHandlerProps: { name: 'total', type: 'number', value: 'left + right' }, cursorDecision: 'commit-all',
  },
  {
    id: 'return-raw', type: 'return', source: 'return user.value + 1',
    expectedHandlerProps: { value: 'user.value + 1' }, cursorDecision: 'commit-all',
  },
  {
    id: 'throw-raw', type: 'throw', source: 'throw new Error("bad")',
    expectedHandlerProps: { value: 'new Error("bad")' }, cursorDecision: 'commit-all',
  },
  {
    id: 'do-raw', type: 'do', source: 'do audit(user, { kind: "login" })',
    expectedHandlerProps: { value: 'audit(user, { kind: "login" })' }, cursorDecision: 'commit-all',
  },
  {
    id: 'if-raw', type: 'if', source: 'if user.active && allowed(user)',
    expectedHandlerProps: { cond: 'user.active && allowed(user)' }, cursorDecision: 'commit-all',
  },
  {
    id: 'while-raw', type: 'while', source: 'while queue.length > 0',
    expectedHandlerProps: { cond: 'queue.length > 0' }, cursorDecision: 'commit-all',
  },
  {
    id: 'doc-singleton', type: 'doc', source: 'doc "hello world"',
    expectedHandlerProps: { text: 'hello world' }, cursorDecision: 'commit-one',
  },
  {
    id: 'theme-bare', type: 'theme', source: 'theme midnight',
    expectedHandlerProps: { name: 'midnight' }, cursorDecision: 'commit-one',
  },
  {
    id: 'import-named', type: 'import', source: 'import { Users, Roles as UserRoles } from "./users.kern"',
    expectedHandlerProps: {
      from: './users.kern', names: 'Users,Roles as UserRoles', __firstClassImport: true,
      __firstClassBindings: [{ name: 'Users' }, { name: 'Roles', as: 'UserRoles' }],
    },
    cursorDecision: 'commit-all',
  },
  {
    id: 'island-kind-name', type: 'island', source: 'island capability stripe',
    expectedHandlerProps: { kind: 'capability', name: 'stripe' }, cursorDecision: 'commit-two',
  },
  {
    id: 'route-method-path', type: 'route', source: 'route GET /users name=listUsers',
    expectedHandlerProps: { method: 'get', path: '/users' }, cursorDecision: 'commit-two',
    expectedFinalProps: { method: 'get', path: '/users', name: 'listUsers' },
  },
  {
    id: 'params-bare-list', type: 'params', source: 'params page:number=1, limit:number=20',
    expectedHandlerProps: {
      items: [
        { name: 'page', type: 'number', default: '1' },
        { name: 'limit', type: 'number', default: '20' },
      ],
    },
    cursorDecision: 'commit-all',
  },
  {
    id: 'auth-bare', type: 'auth', source: 'auth bearer',
    expectedHandlerProps: { mode: 'bearer' }, cursorDecision: 'commit-one',
  },
  {
    id: 'validate-bare', type: 'validate', source: 'validate UserInput',
    expectedHandlerProps: { schema: 'UserInput' }, cursorDecision: 'commit-one',
  },
  {
    id: 'error-status-message', type: 'error', source: 'error 404 "missing"',
    expectedHandlerProps: { status: 404, message: 'missing' }, cursorDecision: 'commit-two',
  },
  {
    id: 'derive-bare', type: 'derive', source: 'derive fullName',
    expectedHandlerProps: { name: 'fullName' }, cursorDecision: 'commit-one',
  },
  {
    id: 'guard-bare', type: 'guard', source: 'guard authenticated',
    expectedHandlerProps: { name: 'authenticated' }, cursorDecision: 'commit-one',
  },
  {
    id: 'effect-bare', type: 'effect', source: 'effect storage',
    expectedHandlerProps: { name: 'storage' }, cursorDecision: 'commit-one',
  },
  {
    id: 'strategy-bare', type: 'strategy', source: 'strategy retry',
    expectedHandlerProps: { name: 'retry' }, cursorDecision: 'commit-one',
  },
  {
    id: 'trigger-bare', type: 'trigger', source: 'trigger schedule',
    expectedHandlerProps: { kind: 'schedule' }, cursorDecision: 'commit-one',
  },
  {
    id: 'respond-status', type: 'respond', source: 'respond 201 json=created',
    expectedHandlerProps: { status: 201 }, cursorDecision: 'commit-one',
    expectedFinalProps: { status: 201, json: 'created' },
  },
  {
    id: 'expect-mode', type: 'expect', source: 'expect codegen contains="function greet"',
    expectedHandlerProps: { codegen: true }, cursorDecision: 'commit-one',
    expectedFinalProps: { codegen: true, contains: 'function greet' },
  },
  {
    id: 'rule-id', type: 'rule', source: 'rule no-eval severity=error',
    expectedHandlerProps: { id: 'no-eval' }, cursorDecision: 'commit-one',
    expectedFinalProps: { id: 'no-eval', severity: 'error' },
  },
  {
    id: 'message-template', type: 'message', source: 'message "hello {{name}}"',
    expectedHandlerProps: { template: 'hello {{name}}' }, cursorDecision: 'commit-one',
  },
  {
    id: 'middleware-list', type: 'middleware', source: 'middleware auth, audit',
    expectedHandlerProps: { names: ['auth', 'audit'] }, cursorDecision: 'commit-all',
  },
]);

export const KEYWORD_HANDLER_FALLBACK_FIXTURES = Object.freeze([
  { id: 'fn-invalid-rewind', type: 'fn', source: 'fn name=legacy returns=void', expectedHandlerProps: {}, cursorDecision: 'rewind' },
  { id: 'let-legacy-rewind', type: 'let', source: 'let name=value value="1"', expectedHandlerProps: {}, cursorDecision: 'rewind' },
  { id: 'return-key-value-noop', type: 'return', source: 'return value=ready', expectedHandlerProps: {}, cursorDecision: 'noop' },
  { id: 'doc-raw-rewind', type: 'doc', source: 'doc hello brave world', expectedHandlerProps: { text: 'hello brave world' }, cursorDecision: 'rewind-commit-all' },
  { id: 'import-default-equals-rewind', type: 'import', source: 'import default=Widget from=lib', expectedHandlerProps: {}, cursorDecision: 'rewind' },
  { id: 'route-invalid-rewind', type: 'route', source: 'route TRACE /users', expectedHandlerProps: {}, cursorDecision: 'rewind' },
  { id: 'expect-invalid-rewind', type: 'expect', source: 'expect runtime value=true', expectedHandlerProps: {}, cursorDecision: 'rewind' },
  { id: 'middleware-equals-noop', type: 'middleware', source: 'middleware name=auth', expectedHandlerProps: {}, cursorDecision: 'noop' },
]);

export const KEYWORD_HANDLER_EDGE_FIXTURES = Object.freeze([
  {
    id: 'fn-nested-signature-and-dynamic-props',
    type: 'fn',
    source: 'fn map<T extends Box<Result<string, number>>>(value: Box<Result<string, number>>, mapper: (x: string, y: number) => Result<string, number>): Promise<Result<string, number>> async=true constructor=ctor __proto__=ignored toString=stringer',
    expectedHandlerProps: {
      name: 'map',
      generics: '<T extends Box<Result<string, number>>>',
      params: 'value:Box<Result<string, number>>,mapper:(x: string, y: number)=> Result<string, number>',
      returns: 'Promise<Result<string, number>>',
      async: true,
      constructor: 'ctor',
      toString: 'stringer',
      __firstClassSyntax: true,
    },
  },
  {
    id: 'let-top-level-assignment-after-arrow-type',
    type: 'let',
    source: 'let callback: (value: number) => Result<string, Error> = makeCallback({ fallback: "a=b" })',
    expectedHandlerProps: {
      name: 'callback',
      type: '(value: number) => Result<string, Error>',
      value: 'makeCallback({ fallback: "a=b" })',
    },
  },
  {
    id: 'import-foreign-registry',
    type: 'import',
    source: 'import npm "@scope/pkg" as Pkg mode=lazy constructor=ctor __proto__=ignored toString=stringer',
    expectedHandlerProps: {
      from: '@scope/pkg', package: '@scope/pkg', registry: 'npm', target: 'ts',
      __firstClassImport: true, default: 'Pkg', mode: 'lazy', constructor: 'ctor', toString: 'stringer',
    },
  },
  {
    id: 'import-side-effect', type: 'import', source: 'import "./side.js"',
    expectedHandlerProps: { from: './side.js', __firstClassImport: true },
  },
  {
    id: 'import-legacy-name', type: 'import', source: 'import Widget',
    expectedHandlerProps: { name: 'Widget' },
  },
  {
    id: 'import-legacy-default-name', type: 'import', source: 'import default Widget',
    expectedHandlerProps: { default: true, name: 'Widget' },
  },
  {
    id: 'import-type-bindings', type: 'import',
    source: 'import type { User, Role as UserRole } from "./types.js"',
    expectedHandlerProps: {
      from: './types.js', names: 'User,Role as UserRole', types: true, __firstClassImport: true,
      __firstClassBindings: [{ name: 'User' }, { name: 'Role', as: 'UserRole' }],
    },
  },
  {
    id: 'params-nested-comma-defaults', type: 'params',
    source: 'params tags:string[]=["a","b"], callback:Fn=(x,y)=>x',
    expectedHandlerProps: {
      items: [
        { name: 'tags', type: 'string[]', default: '["a","b"]' },
        { name: 'callback', type: 'Fn', default: '(x,y)=>x' },
      ],
    },
  },
  {
    id: 'params-documented-array', type: 'params',
    source: 'params items="[{name:page,type:number,default:1},{name:sort,type:string,default:\'relevance\'},{name:broken}]"',
    expectedHandlerProps: {
      items: [
        { name: 'page', type: 'number', default: '1' },
        { name: 'sort', type: 'string', default: '\'relevance\'' },
      ],
    },
  },
  {
    id: 'return-stitched-logical-newline', type: 'return', source: 'return first +\n  second',
    expectedHandlerProps: { value: 'first +\n  second' },
  },
  {
    id: 'doc-astral-width', type: 'doc', source: 'doc "hello 🚀"',
    expectedHandlerProps: { text: 'hello 🚀' },
  },
]);

export const KEYWORD_HANDLER_NUMERIC_FIXTURES = Object.freeze([
  { id: 'error-fraction', type: 'error', source: 'error 1.5 "fraction"', expectedHandlerProps: { status: 1, message: 'fraction' } },
  { id: 'respond-separator', type: 'respond', source: 'respond 1_000', expectedHandlerProps: { status: 1 } },
  { id: 'respond-hex-radix-ten', type: 'respond', source: 'respond 0x10', expectedHandlerProps: { status: 0 } },
  { id: 'respond-binary-radix-ten', type: 'respond', source: 'respond 0b10', expectedHandlerProps: { status: 0 } },
  { id: 'respond-bigint-token', type: 'respond', source: 'respond 99n', expectedHandlerProps: { status: 99 } },
  { id: 'respond-leading-dot', type: 'respond', source: 'respond .5', expectedHandlerProps: { status: Number.NaN } },
  { id: 'respond-invalid-number-noop', type: 'respond', source: 'respond nope', expectedHandlerProps: {} },
]);
