import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { resolve } from 'node:path';
import test from 'node:test';

import { DEFAULT_TIMEOUT_MS } from '../kern-5-admission-census/sweep.mjs';
import {
  BASE_ADMISSION_DIGEST,
  BASE_ADMITTED_DIGEST,
  CENSUS_HARNESS_TIMEOUT_MS,
  REPO_ROOT,
  SCHEDULER_TIMEOUT_MS,
  bytes,
  json,
  policy,
  sha256,
} from './support.mjs';

const ADMITTED = 'scripts/kern-5-admission-census/admitted.json';
const ADMISSION = 'scripts/kern-5-admission-census/admission.json';
const ADAPTER = 'packages/core/dist/frontend-projection-assets/adapter.cjs';

test('B4: the admission ratchet is byte-identical', () => {
  assert.equal(sha256(bytes(ADMITTED)), BASE_ADMITTED_DIGEST);
});

test('B4: the ratchet still holds exactly the one file this slice cannot reach', () => {
  const ratchet = json(ADMITTED);
  assert.equal(ratchet.admitted.length, 1);
  assert.equal(ratchet.admitted[0].file, 'examples/kern-5-preview-app/ui.kern');
});

test('B4: the recorded census report is not regenerated by this slice', () => {
  assert.equal(sha256(bytes(ADMISSION)), BASE_ADMISSION_DIGEST);
});

test('B4: the projection stage stays bounded far below the census harness timeout', () => {
  const adapter = createRequire(import.meta.url)(resolve(REPO_ROOT, ADAPTER));
  assert.equal(policy().scheduler.timeoutMs, SCHEDULER_TIMEOUT_MS);
  assert.equal(adapter.limits.ipc.timeoutMs, SCHEDULER_TIMEOUT_MS);
  assert.equal(DEFAULT_TIMEOUT_MS, CENSUS_HARNESS_TIMEOUT_MS);
  assert.ok(adapter.limits.ipc.timeoutMs * 2 < DEFAULT_TIMEOUT_MS,
    'a raised work budget must not be able to push a probe into a census timeout row');
});
