export const VALID_FIXTURES = Object.freeze([
  { id: 'empty', source: '' },
  { id: 'tokens', source: 'view name=Home, /route $theme\n' },
  { id: 'numbers', source: '1 0x1f 0b10 0o7 4.2 5n .5\n' },
  { id: 'number-adjacent-suffixes', source: '1n2 0x1n2 1.5n2 0b102 0o78\n' },
  { id: 'comments', source: '# full\r\nurl=http://x // tail\n' },
  { id: 'quotes', source: 'text value="a\\"b" other=\'c\\\'d\'\n' },
  { id: 'quote-continuation', source: 'text value="first\r\nsecond"\ntext value=\'third\nfourth\'\n' },
  { id: 'quote-middle', source: 'text value="first\nmiddle\nlast"\n' },
  { id: 'quote-lone-cr', source: 'text value="a\rb"\n' },
  { id: 'quote-escaped-lone-cr', source: 'text value="a\\\rb"\n' },
  { id: 'expression', source: 'text value={{ call("}}", {{ nested }}) }}\n' },
  { id: 'expression-double-quote-seam', source: 'text value={{ "a\\"b" "\\\\" "\\x22" "\\u0022" "😀 }}" }}\n' },
  { id: 'expression-single-quote-seam', source: "text value={{ 'a\\'b' '\\\\' '\\x22' '\\u0022' '😀 }}' }}\n" },
  { id: 'expression-continuation', source: 'text value={{ first\r\nmiddle\nlast }}\n' },
  { id: 'expression-escaped-crlf', source: 'text value={{ "a\\\r\nb" }}\r\n' },
  { id: 'expression-lone-cr', source: 'text value={{ "a\rb" }}\n' },
  { id: 'expression-escaped-lone-cr', source: 'text value={{ "a\\\rb" }}\n' },
  { id: 'style-quote', source: 'view { content:"}" color:red }\n' },
  { id: 'fence-inline', source: 'handler <<<const x = "😀";>>>\n' },
  { id: 'fence-inline-double-chevron', source: 'handler <<<a>>b>>>\n' },
  { id: 'fence-inline-lone-cr', source: 'handler <<<a\rb>>>\n' },
  { id: 'fence-lines', source: 'handler <<<\r\n  raw 😀\r\n  >>>\n' },
  { id: 'fence-lines-lone-cr', source: 'handler <<<\r\n  a\rb\r\n  >>>\n' },
  { id: 'fence-lines-cr-indent', source: 'handler <<<\n\r >>>\n>>>\n' },
  { id: 'fence-orphan-closer', source: '>>>\n' },
  { id: 'unknown', source: '\uFEFF@decorator\rbare\r\n' },
]);

export const FAILURE_FIXTURES = Object.freeze([
  { code: 'UNCLOSED_STYLE', id: 'style-newline', source: 'view { color:red\nnext\n' },
  { code: 'UNCLOSED_STYLE', id: 'style-lone-cr', source: 'view { content:"a\rb" }\n' },
  { code: 'UNCLOSED_STYLE', id: 'style-escaped-lf', source: 'view { content:"x\\\ny" }\n' },
  { code: 'UNCLOSED_STYLE', id: 'style-escaped-crlf', source: 'view { content:"x\\\r\ny" }\r\n' },
  { code: 'UNCLOSED_STYLE', id: 'style-escaped-lone-cr', source: 'view { content:"x\\\ry" }\n' },
  { code: 'UNCLOSED_STRING', id: 'quote-eof', source: 'text value="open' },
  { code: 'UNCLOSED_EXPR', id: 'expr-eof', source: 'text value={{ open' },
  { code: 'UNEXPECTED_TOKEN', id: 'fence-eof', source: 'handler <<<open' },
]);
