export const VALID_FIXTURES = Object.freeze([
  { id: 'identifier', rules: ['primary:identifier', 'kind:identifier'], source: 'answer' },
  { id: 'null', rules: ['primary:null', 'kind:null'], source: 'null' },
  { id: 'boolean', rules: ['primary:boolean', 'kind:boolean'], source: 'true' },
  { id: 'integer', rules: ['primary:integer', 'kind:integer'], source: '42' },
  { id: 'decimal', rules: ['primary:decimal', 'kind:decimal'], source: '3.14' },
  { id: 'text', rules: ['primary:text', 'kind:text', 'text:decoded-escapes'], source: '"\\x41\\u0042\\u{1F600}"' },
  { id: 'parenthesized', rules: ['primary:parenthesized'], source: '(answer)' },
  { id: 'list', rules: ['primary:list', 'kind:list', 'collection:list-trailing-comma'], source: '[a, b,]' },
  { id: 'record', rules: ['primary:record', 'kind:record', 'collection:record-key-forms'], source: '{a, 2: b, "c": d,}' },
  { id: 'member', rules: ['kind:member', 'postfix:member:false'], source: 'a.b' },
  { id: 'optional-member', rules: ['postfix:member:true'], source: 'a?.b' },
  { id: 'index', rules: ['kind:index', 'postfix:index:false'], source: 'a[b]' },
  { id: 'optional-index', rules: ['postfix:index:true'], source: 'a?.[b]' },
  { id: 'call', rules: ['kind:call', 'postfix:call:false'], source: 'f(a, b)' },
  { id: 'optional-call', rules: ['postfix:call:true'], source: 'f?.(a)' },
  { id: 'new-map', rules: ['kind:new', 'constructor:Map'], source: 'new Map()' },
  { id: 'new-error', rules: ['constructor:Error'], source: 'new Error(problem)' },
  { id: 'lambda-bare', rules: ['kind:lambda', 'lambda:identifier'], source: 'a => b => c' },
  { id: 'lambda-list', rules: ['lambda:identifier-list', 'lambda:empty-list'], source: '() => ((a, b) => a)' },
  { id: 'binary', rules: ['kind:binary', 'precedence:binary'], source: 'a + b * c' },
  { id: 'unary', rules: ['kind:unary', 'precedence:unary-power'], source: '(-a) ** b' },
  { id: 'conditional', rules: ['kind:conditional', 'precedence:conditional'], source: 'a ? b : c ? d : e' },
  { id: 'nested-postfix', rules: ['postfix:left-chain'], source: 'a?.b[c]?.(d)' },
  { id: 'nested-collections', rules: ['collection:nested'], source: '[{a: [b, c]}, d]' },
  { id: 'whitespace-newlines', rules: ['lexer:whitespace'], source: '\t(a\n +\r\n b)\t' },
  { id: 'astral-span', rules: ['span:astral'], source: '"😀" + "x"' },
  { id: 'surrogate-pair', rules: ['text:surrogate-pair'], source: '"\\uD83D\\uDE00"' },
  { id: 'terminator-in-string', rules: ['text:terminator'], source: '"}} ] ) , :"' },
  { id: 'nullish-grouped', rules: ['restriction:nullish-logical-parenthesized'], source: '(a ?? b) || c' },
]);

export const FAILURE_FIXTURES = Object.freeze([
  { family: 'assignment', source: 'a = b' },
  { family: 'await', source: 'await a' },
  { family: 'bigint', source: '1n' },
  { family: 'block-lambda', source: 'a => { b }' },
  { family: 'host-closure', source: 'function() { a }' },
  { family: 'non-null', source: 'a!' },
  { family: 'propagation', source: 'a?' },
  { family: 'record-spread', source: '{...a}' },
  { family: 'regex', source: '/x/' },
  { family: 'spread', source: '[...a]' },
  { family: 'template', source: '`x`' },
  { family: 'type-assertion', source: 'a as T' },
  { family: 'typed-call', source: 'f<T>(x)' },
  { family: 'typed-lambda', source: '(a: T) => a' },
  { family: 'undefined', source: 'undefined' },
  { family: 'unlisted-constructor', source: 'new Date()' },
]);
