export const GENERIC_PROPERTY_STYLE_THEME_FIXTURES = Object.freeze([
  { id: 'zero-styles', source: 'screen a=one $base b="two"' },
  { id: 'basic-style', source: 'screen {bg:red,p:16}' },
  { id: 'multiple-styles', source: 'screen {bg:red} $base {fg:white}' },
  { id: 'properties-around-style', source: 'screen a=one {bg:red} b=two' },
  { id: 'empty-before-style', source: 'screen a={bg:red} b=two' },
  { id: 'bare-before-style', source: 'screen a=bare{bg:red} b=two' },
  { id: 'themes-around-style', source: 'screen $base {bg:red} $accent' },
  { id: 'cross-block-last-write', source: 'screen {a:1,:press:bg:red} {a:2,:press:bg:blue}' },
  { id: 'quoted-commas', source: 'screen {a:"x,y",b:rgb(1,2,3)}' },
  { id: 'nested-parens', source: 'screen {a:func(1,(2,3)),b:4}' },
  { id: 'negative-depth', source: 'screen {a:x),b:2}' },
  { id: 'escaped-comma', source: 'screen {a:one\\,two,b:3}' },
  { id: 'trailing-backslash', source: 'screen {a:tail\\}' },
  { id: 'empty-segments', source: 'screen {,a:1,, ,b:2,}' },
  { id: 'pair-precedence', source: 'screen {:press:bg:#005,"backdrop-filter":"blur(8px)",colon::x,bad}' },
  { id: 'empty-values-and-key', source: 'screen {empty:,quoted:"", :blank}' },
  { id: 'quoted-unescape-order', source: 'screen {a:"x\\\"y",b:"x\\\\y"}' },
  { id: 'unsafe-visible-state', source: 'screen {__proto__:x,constructor:y,toString:z,:press:__proto__:red,:press:constructor:c,:press:toString:t,:constructor:bg:blue}' },
  { id: 'integer-key-order', source: 'screen {b:1,2:two,01:leading,0:zero,4294967294:max,4294967295:over,1:one,-0:neg,a:2}' },
  { id: 'pseudo-integer-key-order', source: 'screen {:press:b:1,:press:2:two,:press:01:leading,:press:0:zero,:press:4294967294:max,:press:4294967295:over}' },
  { id: 'duplicate-with-integer', source: 'screen {2:a,b:x,2:c,b:y}' },
  { id: 'quoted-style-like-text', source: 'screen a="{bg:red}"' },
  { id: 'expression-style-like-text', source: 'screen a={{ "{bg:red}" }}' },
  { id: 'unclosed-style', source: 'screen {a:"unterminated,b:2' },
  { id: 'unicode-value', source: 'screen {label:"😀é"}' },
  { id: 'unknown-node-style', source: 'm4167_unknown {bg:red}' },
  { id: 'inline-comment-style-like', source: 'screen {bg:red} # {ignored:yes}' },
  { id: 'dropped-node', source: '123 {bg:red}' },
  { id: 'unexpected-before-style', source: 'screen ) {bg:red}' },
  { id: 'missing-equals-before-style', source: 'screen bare {bg:red}' },
  { id: 'property-limit-before-style', source: 'screen a0=0 a1=1 a2=2 a3=3 a4=4 a5=5 a6=6 a7=7 a8=8 {bg:red}' },
  { id: 'theme-limit-before-style', source: 'screen $t0 $t1 $t2 $t3 $t4 $t5 $t6 $t7 $t8 {bg:red}' },
]);
