/**
 * Phase-2 corpus seed — routes `bitwise` and `logical` (+ S5 iterable-position
 * logical rows). Faithful transcription of `.agon-goals/phase2-corpus-seed.md`.
 *
 * Each case is an explicit, stable, named record. `expectedFirstCapture` is the
 * Gate-INT expectation for the first real capture; for slice 0 (no routes
 * flipped) it documents intent and seeds the ratchet, it is not yet enforced as
 * production routing.
 *
 * @typedef {'expr'|'stmt'|'route'|'route-pipeline'|'whole-file'} Phase2Kind
 * @typedef {'conformance:expr'|'conformance:kern-props'|'repo-kern:value-props'|'hand-authored'} Phase2SourceKind
 * @typedef {'EXPRESSION'|'PROSE_NOT_EXPR'|'ESCAPED_ARTIFACT'|'EXCLUDED_NONDETERMINISTIC'} Phase2Denominator
 * @typedef {'BYTE_EQUAL'|'RUNTIME_EQUAL_BYTE_DIFF'|'AST_BLOCKED'|'LEGACY_BLOCKED'|'BOTH_BLOCKED_SAME'|'BOTH_BLOCKED_DIFF'|'RUNTIME_DIVERGE'|'SEMANTIC_BOTH_WRONG'|'CAPTURE_ERROR'} Phase2Verdict
 *
 * @typedef {object} Phase2Case
 * @property {string} id stable kebab id, used in snapshot paths
 * @property {Phase2Kind} kind
 * @property {string} source expression / handler body / route source
 * @property {Phase2SourceKind} sourceKind
 * @property {string} [location] provenance for review
 * @property {unknown} [bindings] runner bindings: { locals?, helpers? }
 * @property {unknown} [expected] semantic oracle (runner-prelude shorthand)
 * @property {string[]} tags required-coverage tags
 * @property {string[]} routes route keys this case exercises
 * @property {boolean} deterministic
 * @property {Phase2Denominator} denominator
 * @property {Phase2Verdict} [expectedFirstCapture]
 * @property {string} [notes]
 */

/** @type {Phase2Case[]} */
export const BITWISE_CASES = [
  {
    id: 'bitwise-or-sign-bit',
    kind: 'expr',
    source: 'a | z',
    sourceKind: 'conformance:expr',
    location: 'scripts/conformance.mjs:423',
    bindings: { locals: { a: 2147483648, z: 0 } },
    expected: -2147483648,
    tags: ['bitwise', 'int32', 'sign-bit', 'conformance'],
    routes: ['bitwise'],
    deterministic: true,
    denominator: 'EXPRESSION',
    expectedFirstCapture: 'RUNTIME_EQUAL_BYTE_DIFF',
    notes: 'Runtime should agree; legacy _i32 bytes differ from AST _kern_to_int32 bytes.',
  },
  {
    id: 'bitwise-shr-large-to-zero',
    kind: 'expr',
    source: 'a >> b',
    sourceKind: 'conformance:expr',
    location: 'scripts/conformance.mjs:425',
    bindings: { locals: { a: 8589934592, b: 1 } },
    expected: 0,
    tags: ['bitwise', 'shift', 'toint32-left', 'conformance'],
    routes: ['bitwise'],
    deterministic: true,
    denominator: 'EXPRESSION',
    expectedFirstCapture: 'RUNTIME_EQUAL_BYTE_DIFF',
    notes: 'Kills missing left ToInt32 before arithmetic shift.',
  },
  {
    id: 'bitwise-shl-count-mask',
    kind: 'expr',
    source: 'a << b',
    sourceKind: 'conformance:expr',
    location: 'scripts/conformance.mjs:429',
    bindings: { locals: { a: 1, b: 33 } },
    expected: 2,
    tags: ['bitwise', 'shift', 'count-mask', 'conformance'],
    routes: ['bitwise'],
    deterministic: true,
    denominator: 'EXPRESSION',
    expectedFirstCapture: 'RUNTIME_EQUAL_BYTE_DIFF',
    notes: 'Kills unmasked Python shift count.',
  },
  {
    id: 'bitwise-computed-sum-or-wrap',
    kind: 'expr',
    source: '(a + b) | z',
    sourceKind: 'conformance:expr',
    location: 'scripts/conformance.mjs:430',
    bindings: { locals: { a: 2147483647, b: 1, z: 0 } },
    expected: -2147483648,
    tags: ['bitwise', 'computed-left', 'wraparound', 'conformance'],
    routes: ['bitwise'],
    deterministic: true,
    denominator: 'EXPRESSION',
    expectedFirstCapture: 'RUNTIME_EQUAL_BYTE_DIFF',
    notes: 'Kills literal-only wrapping; ToInt32 must apply at operator boundary.',
  },
  {
    id: 'bitwise-not-string-float',
    kind: 'expr',
    source: '~a',
    sourceKind: 'conformance:expr',
    location: 'scripts/conformance.mjs:443',
    bindings: { locals: { a: '-3.9' } },
    expected: 2,
    tags: ['bitwise', 'unary', 'tonumber', 'string-float', 'conformance'],
    routes: ['bitwise'],
    deterministic: true,
    denominator: 'EXPRESSION',
    expectedFirstCapture: 'RUNTIME_EQUAL_BYTE_DIFF',
    notes: 'Kills missing JS ToNumber + truncate-toward-zero.',
  },
  {
    id: 'bitwise-ushr-negative-zero-shift',
    kind: 'expr',
    source: 'a >>> b',
    sourceKind: 'conformance:expr',
    location: 'scripts/conformance.mjs:1123',
    bindings: { locals: { a: -1, b: 0 } },
    expected: 4294967295,
    tags: ['bitwise', 'unsigned-shift', 'uint32-result', 'conformance'],
    routes: ['bitwise'],
    deterministic: true,
    denominator: 'EXPRESSION',
    expectedFirstCapture: 'RUNTIME_EQUAL_BYTE_DIFF',
    notes: 'Kills raw Python signed >> for >>>.',
  },
  {
    id: 'bitwise-precedence-or-before-andand',
    kind: 'expr',
    source: '1 | 2 && 0',
    sourceKind: 'hand-authored',
    location: 'packages/core/tests/bitwise-toint32-operators.test.ts:119',
    bindings: {},
    expected: 0,
    tags: ['bitwise', 'logical-boundary', 'precedence', 'hand-authored-edge'],
    routes: ['bitwise', 'logical'],
    deterministic: true,
    denominator: 'EXPRESSION',
    expectedFirstCapture: 'RUNTIME_EQUAL_BYTE_DIFF',
    notes: '`|` binds tighter than `&&`; AST bytes should differ because S6 helper route is explicit.',
  },
  {
    id: 'bitwise-eval-once-ushr-or-log',
    kind: 'expr',
    source: '(mark("a", -1) >>> mark("b", 0)) | mark("c", 0)',
    sourceKind: 'hand-authored',
    location: 'packages/python/tests/bitwise-toint32-operators-python.test.ts:188',
    bindings: { helpers: ['mark'], locals: {} },
    expected: { value: -1, calls: ['a', 'b', 'c'] },
    tags: ['bitwise', 'unsigned-shift', 'eval-once', 'left-to-right', 'hand-authored-edge'],
    routes: ['bitwise'],
    deterministic: true,
    denominator: 'EXPRESSION',
    expectedFirstCapture: 'RUNTIME_EQUAL_BYTE_DIFF',
    notes: 'Executed fixture must assert both value and call log.',
  },
  {
    id: 'bitwise-nested-mod-ushr-composition',
    kind: 'expr',
    source: '((a % b) >>> c) | z',
    sourceKind: 'hand-authored',
    location: 'phase2-corpus-seed:bitwise',
    bindings: { locals: { a: -7, b: 3, c: 0, z: 0 } },
    expected: -1,
    tags: ['bitwise', 'modulo', 'unsigned-shift', 'composition', 'hand-authored-edge'],
    routes: ['bitwise'],
    deterministic: true,
    denominator: 'EXPRESSION',
    expectedFirstCapture: 'RUNTIME_EQUAL_BYTE_DIFF',
    notes: 'Non-conformance edge: JS -7 % 3 is -1; then >>>0 then |0 returns -1.',
  },
  {
    id: 'bitwise-generic-surplus-gt-boundary',
    kind: 'expr',
    source: 'f<Bar<Baz>>>(x)',
    sourceKind: 'hand-authored',
    location: 'packages/core/tests/bitwise-toint32-operators.test.ts:73',
    bindings: {},
    expected: { parseShape: 'not-call-with-typeArgs' },
    tags: ['bitwise', 'parser-boundary', 'generics', 'surplus-gt', 'hand-authored-edge'],
    routes: ['bitwise'],
    deterministic: true,
    denominator: 'EXPRESSION',
    expectedFirstCapture: 'BOTH_BLOCKED_SAME',
    notes: 'Parse-boundary row: surplus >>> must not be swallowed as generic close. Does not count toward runtime ratchetCount until parse-only cases get a capture adapter.',
  },
];

/** @type {Phase2Case[]} */
export const LOGICAL_CASES = [
  {
    id: 'logical-and-basic-expression',
    kind: 'expr',
    source: 'a && b',
    sourceKind: 'hand-authored',
    location: 'packages/python/tests/native-handlers-slice2-python.test.ts:103',
    bindings: { locals: { a: 'left', b: 'right' } },
    expected: 'right',
    tags: ['logical', 'and', 'result-value', 'existing-test'],
    routes: ['logical'],
    deterministic: true,
    denominator: 'EXPRESSION',
    expectedFirstCapture: 'RUNTIME_EQUAL_BYTE_DIFF',
    notes: 'Runtime agrees for truthy strings, but AST walrus bytes differ from legacy `and`.',
  },
  {
    id: 'logical-or-basic-expression',
    kind: 'expr',
    source: 'a || b',
    sourceKind: 'hand-authored',
    location: 'packages/python/tests/native-handlers-slice2-python.test.ts:107',
    bindings: { locals: { a: '', b: 'fallback' } },
    expected: 'fallback',
    tags: ['logical', 'or', 'result-value', 'existing-test'],
    routes: ['logical'],
    deterministic: true,
    denominator: 'EXPRESSION',
    expectedFirstCapture: 'RUNTIME_EQUAL_BYTE_DIFF',
    notes: 'Runtime agrees for empty string, but AST walrus bytes differ from legacy `or`.',
  },
  {
    id: 'logical-precedence-or-and',
    kind: 'expr',
    source: 'a || b && c',
    sourceKind: 'hand-authored',
    location: 'packages/core/tests/expression.test.ts:358',
    bindings: { locals: { a: '', b: '0', c: 'right' } },
    expected: 'right',
    tags: ['logical', 'or', 'and', 'precedence', 'existing-test'],
    routes: ['logical'],
    deterministic: true,
    denominator: 'EXPRESSION',
    expectedFirstCapture: 'RUNTIME_EQUAL_BYTE_DIFF',
    notes: '`&&` binds tighter than `||`; runtime agrees but AST output should be nested walrus.',
  },
  {
    id: 'logical-call-child-parenthesized',
    kind: 'expr',
    source: '(factory || fallback)()',
    sourceKind: 'hand-authored',
    location: 'packages/core/tests/expression.test.ts:392',
    bindings: { locals: { factory: null }, helpers: ['callableFallback'] },
    expected: { value: 'callable-result', calls: ['fallback'] },
    tags: ['logical', 'or', 'call-child', 'parentheses', 'existing-test'],
    routes: ['logical'],
    deterministic: true,
    denominator: 'EXPRESSION',
    expectedFirstCapture: 'RUNTIME_EQUAL_BYTE_DIFF',
    notes: 'Capture harness needs callable bindings; row protects parenthesized logical child under call. callableFallback() logs "fallback" and returns "callable-result".',
  },
  {
    id: 'logical-container-or-legacy-bug',
    kind: 'expr',
    source: 'a || b',
    sourceKind: 'hand-authored',
    location: 'slice5 oracle: [] || "x"',
    bindings: { locals: { a: [], b: 'x' } },
    expected: [],
    tags: ['logical', 'or', 'result-value', 'container-truthy', 'legacy-bug', 'hand-authored-edge'],
    routes: ['logical'],
    deterministic: true,
    denominator: 'EXPRESSION',
    expectedFirstCapture: 'LEGACY_BLOCKED',
    notes: 'INTENTIONAL AST-first divergence seed: Python legacy `[] or "x"` returns "x"; S5 AST returns [] via _kern_truthy. Proves the ratchet detects real divergence, not tautology.',
  },
  {
    id: 'logical-nan-and-legacy-bug',
    kind: 'expr',
    source: 'a && b',
    sourceKind: 'hand-authored',
    location: 'slice5 oracle: NaN && "right"',
    bindings: { locals: { a: { kind: 'number', value: 'NaN' }, b: 'right' } },
    expected: { kind: 'number', value: 'NaN' },
    tags: ['logical', 'and', 'nan-falsy', 'legacy-bug', 'hand-authored-edge'],
    routes: ['logical'],
    deterministic: true,
    denominator: 'EXPRESSION',
    expectedFirstCapture: 'LEGACY_BLOCKED',
    notes: 'Typed canonicalizer must preserve NaN; Python legacy treats float("nan") truthy and selects right.',
  },
  {
    id: 'logical-precedence-calls-log',
    kind: 'expr',
    source: 'mark("A", "") || mark("B", "0") && mark("C", "right")',
    sourceKind: 'hand-authored',
    location: 'slice5-crosscheck.md',
    bindings: { helpers: ['mark'], locals: {} },
    expected: { value: 'right', calls: ['A', 'B', 'C'] },
    tags: ['logical', 'or', 'and', 'precedence', 'eval-once', 'call-log', 'hand-authored-edge'],
    routes: ['logical'],
    deterministic: true,
    denominator: 'EXPRESSION',
    expectedFirstCapture: 'RUNTIME_EQUAL_BYTE_DIFF',
    notes: 'Checklist kill row: verifies precedence and exact left-to-right short-circuit log.',
  },
  {
    id: 'logical-impure-member-left-single-eval',
    kind: 'expr',
    source: 'getObj().flag || mark("R", "fallback")',
    sourceKind: 'hand-authored',
    location: 'slice5-crosscheck.md',
    bindings: { helpers: ['getObj', 'mark'], locals: {} },
    expected: { value: 'fallback', calls: ['getObj', 'R'] },
    tags: ['logical', 'or', 'member-left', 'eval-once', 'hand-authored-edge'],
    routes: ['logical'],
    deterministic: true,
    denominator: 'EXPRESSION',
    expectedFirstCapture: 'RUNTIME_EQUAL_BYTE_DIFF',
    notes: 'S5 AST must bind receiver once before _kern_truthy test; legacy may runtime-agree but not byte-agree.',
  },
  {
    id: 'logical-impure-index-left-single-eval',
    kind: 'expr',
    source: 'arr[mark("I", 0)] || mark("R", "fallback")',
    sourceKind: 'hand-authored',
    location: 'slice5-crosscheck.md',
    bindings: { helpers: ['mark'], locals: { arr: [[]] } },
    expected: { value: [], calls: ['I'] },
    tags: ['logical', 'or', 'index-left', 'container-truthy', 'eval-once', 'hand-authored-edge'],
    routes: ['logical'],
    deterministic: true,
    denominator: 'EXPRESSION',
    expectedFirstCapture: 'LEGACY_BLOCKED',
    notes: 'Python legacy sees [] as falsy and calls fallback; S5 AST should return [] and skip R.',
  },
  {
    id: 'logical-nullish-boundary-zero',
    kind: 'expr',
    source: '(a ?? b) || c',
    sourceKind: 'hand-authored',
    location: 'packages/core/tests/expression.test.ts:328',
    bindings: { locals: { a: 0, b: 'bad', c: 'fallback' } },
    expected: 'fallback',
    tags: ['logical', 'nullish-boundary', 'or', 'existing-test'],
    routes: ['logical', 'nullish'],
    deterministic: true,
    denominator: 'EXPRESSION',
    expectedFirstCapture: 'RUNTIME_EQUAL_BYTE_DIFF',
    notes: 'Boundary row: logical route must not turn ?? into truthiness; full runtime depends on nullish route.',
  },
  {
    id: 'logical-ternary-consumer-container',
    kind: 'expr',
    source: '(a && b) ? "then" : "else"',
    sourceKind: 'hand-authored',
    location: 'slice5 oracle chained rows',
    bindings: { locals: { a: 'left', b: [] } },
    expected: 'then',
    tags: ['logical', 'and', 'truthy-consumer', 'ternary', 'container-truthy', 'hand-authored-edge'],
    routes: ['logical', 'truthy'],
    deterministic: true,
    denominator: 'EXPRESSION',
    expectedFirstCapture: 'RUNTIME_EQUAL_BYTE_DIFF',
    notes: 'Outer ternary owns final _kern_truthy; logical route must not double-wrap operands.',
  },
];

/**
 * S5-landed iterable-position logical rows (walrus-ban). These assume py_legacy
 * means the pre-S5 body emitter's old Python `and`/`or` route, per the seed doc's
 * first-capture caveat.
 * @type {Phase2Case[]}
 */
export const LOGICAL_ITERABLE_CASES = [
  {
    id: 'logical-iterable-map-empty-list-or',
    kind: 'expr',
    source: 'List.map(a || b, (x) => x)',
    sourceKind: 'hand-authored',
    location: 'S5 r1 iterable-position fix',
    bindings: { locals: { a: [], b: [5] } },
    expected: [],
    tags: ['logical', 'iterable-position', 'map-source', 'container-truthy', 'legacy-bug', 'hand-authored-edge'],
    routes: ['logical', 'array-map'],
    deterministic: true,
    denominator: 'EXPRESSION',
    expectedFirstCapture: 'LEGACY_BLOCKED',
    notes: 'S5 AST maps over []; legacy `[] or [5]` maps over [5]. Also kills walrus-in-comprehension-iterable SyntaxError.',
  },
  {
    id: 'logical-iterable-map-empty-string-or',
    kind: 'expr',
    source: 'List.map(a || b, (x) => x * 2)',
    sourceKind: 'hand-authored',
    location: 'S5 r1 iterable-position fix',
    bindings: { locals: { a: '', b: [3, 4] } },
    expected: [6, 8],
    tags: ['logical', 'iterable-position', 'map-source', 'runtime-equal', 'hand-authored-edge'],
    routes: ['logical', 'array-map'],
    deterministic: true,
    denominator: 'EXPRESSION',
    expectedFirstCapture: 'RUNTIME_EQUAL_BYTE_DIFF',
    notes: 'Runtime agrees for empty-string fallback under old `or`, but S5 bytes use lambda-parameter form instead of walrus in the iterable.',
  },
  {
    id: 'logical-iterable-filter-container-or',
    kind: 'expr',
    source: 'List.filter(a || b, (x) => x)',
    sourceKind: 'hand-authored',
    location: 'S5 r1 iterable-position fix',
    bindings: { locals: { a: [1, 0, 2], b: [9] } },
    expected: [1, 2],
    tags: ['logical', 'iterable-position', 'filter-source', 'container-truthy', 'hand-authored-edge'],
    routes: ['logical', 'array-filter'],
    deterministic: true,
    denominator: 'EXPRESSION',
    expectedFirstCapture: 'RUNTIME_EQUAL_BYTE_DIFF',
    notes: 'Runtime agrees, but emitted source must be walrus-free in the comprehension iterable.',
  },
  {
    id: 'logical-iterable-join-logical-receiver',
    kind: 'expr',
    source: '(a || b).join("-")',
    sourceKind: 'hand-authored',
    location: 'S5 r1 iterable-position fix',
    bindings: { locals: { a: [], b: ['x'] } },
    expected: '',
    tags: ['logical', 'iterable-position', 'join-receiver', 'container-truthy', 'legacy-bug', 'hand-authored-edge'],
    routes: ['logical', 'array-join'],
    deterministic: true,
    denominator: 'EXPRESSION',
    expectedFirstCapture: 'LEGACY_BLOCKED',
    notes: 'S5 AST joins the selected []; legacy `[] or ["x"]` joins fallback. Receiver lands in genexp iterable and must not contain walrus.',
  },
  {
    id: 'logical-iterable-flat-logical-receiver',
    kind: 'expr',
    source: '(a || b).flat()',
    sourceKind: 'hand-authored',
    location: 'S5 r1 iterable-position fix',
    bindings: { locals: { a: [[1], [2, 3]], b: [] } },
    expected: [1, 2, 3],
    tags: ['logical', 'iterable-position', 'flat-receiver', 'container-truthy', 'hand-authored-edge'],
    routes: ['logical', 'array-flat'],
    deterministic: true,
    denominator: 'EXPRESSION',
    expectedFirstCapture: 'RUNTIME_EQUAL_BYTE_DIFF',
    notes: 'Runtime agrees, but receiver must be emitted under the walrus ban for the nested generator heads.',
  },
  {
    id: 'logical-iterable-map-nullish-source',
    kind: 'expr',
    source: 'List.map(mark("F", null) ?? b, (x) => x + 1)',
    sourceKind: 'hand-authored',
    location: 'S5 r1 iterable-position fix',
    bindings: { helpers: ['mark'], locals: { b: [9] } },
    expected: { value: [10], calls: ['F'] },
    tags: ['logical', 'iterable-position', 'nullish-boundary', 'map-source', 'eval-once', 'call-log', 'hand-authored-edge'],
    routes: ['logical', 'nullish', 'array-map'],
    deterministic: true,
    denominator: 'EXPRESSION',
    expectedFirstCapture: 'LEGACY_BLOCKED',
    notes: 'Protects the same ban for impure-left `??`; pre-fix AST compiled invalid walrus in iterable position.',
  },
  {
    id: 'logical-iterable-map-typeof-source',
    kind: 'expr',
    source: 'List.map(typeof a, (c) => c)',
    sourceKind: 'hand-authored',
    location: 'S5 r1 iterable-position fix',
    bindings: { locals: { a: 0 } },
    expected: ['n', 'u', 'm', 'b', 'e', 'r'],
    tags: ['logical', 'iterable-position', 'typeof-boundary', 'map-source', 'hand-authored-edge'],
    routes: ['logical', 'typeof', 'array-map'],
    deterministic: true,
    denominator: 'EXPRESSION',
    expectedFirstCapture: 'LEGACY_BLOCKED',
    notes: 'Protects the same ban for dynamic `typeof`; iterable source must use lambda-parameter form instead of `__k_typeof := ...`.',
  },
  {
    id: 'logical-iterable-map-ternary-source',
    kind: 'expr',
    source: 'List.map(a ? b : c, (x) => x * 10)',
    sourceKind: 'hand-authored',
    location: 'S5 r1 iterable-position fix',
    bindings: { locals: { a: false, b: [1], c: [2, 3] } },
    expected: [20, 30],
    tags: ['logical', 'iterable-position', 'ternary-source', 'parenthesized-source', 'hand-authored-edge'],
    routes: ['logical', 'truthy', 'array-map'],
    deterministic: true,
    denominator: 'EXPRESSION',
    expectedFirstCapture: 'RUNTIME_EQUAL_BYTE_DIFF',
    notes: 'Bare ternary source must be parenthesized so Python does not parse its `if` as a comprehension filter.',
  },
  {
    id: 'logical-iterable-map-call-log',
    kind: 'expr',
    source: 'List.map(mark("A", 0) || mark("B", []) && mark("C", [1]), (x) => x)',
    sourceKind: 'hand-authored',
    location: 'S5 r1 iterable-position fix',
    bindings: { helpers: ['mark'], locals: {} },
    expected: { value: [1], calls: ['A', 'B', 'C'] },
    tags: ['logical', 'iterable-position', 'map-source', 'eval-once', 'call-log', 'hand-authored-edge'],
    routes: ['logical', 'array-map'],
    deterministic: true,
    denominator: 'EXPRESSION',
    expectedFirstCapture: 'RUNTIME_EQUAL_BYTE_DIFF',
    notes: 'Nested lambda-parameter logical form must preserve left-to-right single evaluation and lazy unselected operands.',
  },
];

/** The full Phase-2 slice-0 corpus. */
export const PHASE2_CORPUS = [...BITWISE_CASES, ...LOGICAL_CASES, ...LOGICAL_ITERABLE_CASES];

/**
 * Select corpus cases by route and denominator.
 * @param {{route?: string, denominator?: Phase2Denominator}} [opts]
 * @returns {Phase2Case[]}
 */
export function selectCases(opts = {}) {
  return PHASE2_CORPUS.filter((c) => {
    if (opts.route && !c.routes.includes(opts.route)) return false;
    if (opts.denominator && c.denominator !== opts.denominator) return false;
    return true;
  });
}

/** Assert corpus ids are unique (a duplicate id silently overwrites a snapshot). */
export function assertUniqueIds() {
  const seen = new Set();
  for (const c of PHASE2_CORPUS) {
    if (seen.has(c.id)) throw new Error(`phase2 corpus: duplicate id ${c.id}`);
    seen.add(c.id);
  }
  return seen.size;
}
