/**
 * Default pre-slot policy executor for a freshly generated FastAPI app.
 *
 * A route emitted by fastapi-route.ts calls
 * `request.app.state.execute_kern_policy_slot(entry, "pre", facts)` around
 * its handler. Previously that hook was NEVER installed by the transpiler
 * itself — only the app-behavior-conformance harness's Python leg patched it
 * in, as a test convenience. A real generated app hit an AttributeError (or
 * a 500) on every policy-guarded route. This module implements the
 * KernAppPolicySlotPlan semantics natively in Python (mirroring
 * executePolicySlotPlan in packages/core/src/app-descriptor.ts) so a fresh
 * app is self-sufficient with NO external patching.
 *
 * Secrets stay opaque to guard/.kern code: the executor never exposes key
 * material to the policy plan, only to host-supplied PROVIDER hooks on
 * `app.state`, which the host app may override:
 *
 *   app.state.kern_auth_verifier(verifier_ref, credential, entry) -> bool
 *   app.state.kern_hmac_key_provider(key_ref, entry) -> bytes | str | None
 *   app.state.kern_rag_grounding_adapter(policy, facts, entry) -> dict
 *
 * Every hook may be sync or async. A MISSING provider always DENIES (oracle
 * A4/P6) — it never degrades to allow, and a provider exception denies
 * instead of propagating a 500.
 */
import type { GeneratedArtifact } from '@kernlang/core';

export const FASTAPI_POLICY_RUNTIME_MODULE_BASENAME = 'policy_runtime';

export const FASTAPI_POLICY_RUNTIME_SOURCE = `"""Generated by kern. Default pre-slot policy executor.

Implements the executable guard kinds (auth, hmacSignature, rag-review,
passthrough) natively so a freshly generated FastAPI app enforces policy
without any external patching. Host-supplied PROVIDER hooks on \`app.state\`
remain overridable; a missing provider always DENIES.
"""

import base64
import hashlib
import hmac
import inspect
import re
from typing import Any, Dict, List, Optional


async def _maybe_await(value: Any) -> Any:
    if inspect.isawaitable(value):
        return await value
    return value


def _header_value(headers: Optional[Dict[str, Any]], name: str) -> Optional[str]:
    if not headers:
        return None
    wanted = name.lower()
    for key, value in headers.items():
        if str(key).lower() == wanted:
            return value
    return None


def _failure_status(policy: Dict[str, Any]) -> int:
    props = (policy.get("node") or {}).get("props") or {}
    raw = props.get("failureStatus")
    try:
        value = int(raw)
    except (TypeError, ValueError):
        return 401
    return value if 100 <= value <= 599 else 401


def _denied(policy: Dict[str, Any], diagnostics: Optional[List[str]] = None) -> Dict[str, Any]:
    return {
        "name": policy.get("name"),
        "slot": policy.get("slot", "pre"),
        "kind": policy.get("kind"),
        "action": "deny",
        "status": _failure_status(policy),
        "body": {"error": "policy_denied", "policy": policy.get("name"), "kind": policy.get("kind")},
        "diagnostics": diagnostics or [],
    }


def _allowed(policy: Dict[str, Any]) -> Dict[str, Any]:
    return {"name": policy.get("name"), "slot": policy.get("slot", "pre"), "kind": policy.get("kind"), "action": "allow"}


async def _execute_auth(policy: Dict[str, Any], facts: Dict[str, Any], entry: Dict[str, Any], app_state: Any) -> Dict[str, Any]:
    plan = policy["plan"]
    credential = _header_value(facts.get("headers"), plan["credentialHeader"])
    verifier = getattr(app_state, "kern_auth_verifier", None)
    if not credential or verifier is None:
        return _denied(policy, ["auth credential absent or verifier missing"])
    try:
        ok = await _maybe_await(verifier(plan["verifierRef"], credential, entry))
    except Exception as error:  # guard exception -> deny, fail-closed
        return _denied(policy, [str(error)])
    return _allowed(policy) if ok else _denied(policy, ["auth verifier denied"])


async def _execute_hmac(policy: Dict[str, Any], facts: Dict[str, Any], entry: Dict[str, Any], app_state: Any) -> Dict[str, Any]:
    plan = policy["plan"]
    signature = _header_value(facts.get("headers"), plan["signatureHeader"])
    raw_body = facts.get("rawBody")
    key_provider = getattr(app_state, "kern_hmac_key_provider", None)
    if not signature or key_provider is None or raw_body is None:
        return _denied(policy, ["hmac signature, key provider, or raw body missing"])
    try:
        key = await _maybe_await(key_provider(plan["keyRef"], entry))
    except Exception as error:
        return _denied(policy, [str(error)])
    if key is None:
        return _denied(policy, ["hmac key not provided"])
    key_bytes = key.encode("utf-8") if isinstance(key, str) else bytes(key)
    body_bytes = raw_body.encode("utf-8") if isinstance(raw_body, str) else bytes(raw_body)
    # Mirrors core's normalizeKernHmacAlgorithm (lockstep parity): lowercase,
    # underscore==hyphen, and dashed SHA-2 aliases collapse ('sha-256' ->
    # 'sha256'). Multi-part families keep their separator, mapped to hashlib's
    # underscore convention ('sha3-256' -> 'sha3_256'). The old blanket
    # replace("-", "_") produced 'sha_256', which does not exist on hashlib,
    # so every valid 'sha-256' config denied every request.
    algorithm = str(plan.get("algorithm", "sha256")).strip().lower().replace("_", "-")
    sha_dashed = re.fullmatch(r"sha-(\\d+)", algorithm)
    if sha_dashed is not None:
        algorithm = "sha" + sha_dashed.group(1)
    digestmod = getattr(hashlib, algorithm.replace("-", "_"), None)
    if digestmod is None:
        return _denied(policy, [f"unsupported hmac algorithm '{plan.get('algorithm')}'"])
    expected = hmac.new(key_bytes, body_bytes, digestmod).digest()
    received_str = signature
    prefix = plan.get("prefix")
    if prefix and received_str.startswith(prefix):
        received_str = received_str[len(prefix):]
    try:
        received = bytes.fromhex(received_str) if plan.get("encoding") == "hex" else base64.b64decode(received_str, validate=True)
    except Exception:
        # A malformed/wrong-length signature denies cleanly — never raises.
        return _denied(policy, ["hmac signature mismatch"])
    if len(expected) != len(received) or not hmac.compare_digest(expected, received):
        return _denied(policy, ["hmac signature mismatch"])
    return _allowed(policy)


async def _execute_rag_review(policy: Dict[str, Any], facts: Dict[str, Any], entry: Dict[str, Any], app_state: Any) -> Dict[str, Any]:
    adapter = getattr(app_state, "kern_rag_grounding_adapter", None)
    if adapter is None:
        return _denied(policy, ["rag grounding adapter not provided"])
    try:
        verdict = await _maybe_await(adapter(policy, facts, entry))
    except Exception as error:
        return _denied(policy, [str(error)])
    if not isinstance(verdict, dict) or verdict.get("allow") is not True:
        diagnostics = verdict.get("diagnostics") if isinstance(verdict, dict) else None
        return _denied(policy, diagnostics if isinstance(diagnostics, list) else ["rag verdict denied or malformed"])
    return _allowed(policy)


def create_execute_kern_policy_slot(app: Any):
    """Bind the executor to \`app\` so it can reach \`app.state\` provider hooks
    without smuggling non-serializable state through the \`facts\` contract."""

    async def execute_kern_policy_slot(entry: Dict[str, Any], slot: str, facts: Dict[str, Any]) -> List[Dict[str, Any]]:
        if slot not in ("pre", "post"):
            raise ValueError(f"unknown policy slot '{slot}' (expected pre or post)")
        policies = entry.get("prePolicies" if slot == "pre" else "postPolicies") or []
        executions: List[Dict[str, Any]] = []
        for policy in policies:
            kind = policy.get("kind")
            try:
                if kind == "passthrough":
                    result = _allowed(policy)
                elif kind == "auth":
                    result = await _execute_auth(policy, facts, entry, app.state)
                elif kind == "hmacSignature":
                    result = await _execute_hmac(policy, facts, entry, app.state)
                elif kind == "rag-review":
                    result = await _execute_rag_review(policy, facts, entry, app.state)
                else:
                    # A kind this runtime cannot execute must fail closed —
                    # never fall through to an implicit allow.
                    result = _denied(policy, [f"unsupported policy kind '{kind}'"])
            except Exception as error:
                result = _denied(policy, [str(error)])
            executions.append(result)
            if result["action"] == "deny":
                break
        return executions

    return execute_kern_policy_slot
`;

export function buildFastApiPolicyRuntimeArtifact(): GeneratedArtifact {
  return {
    path: `${FASTAPI_POLICY_RUNTIME_MODULE_BASENAME}.py`,
    content: FASTAPI_POLICY_RUNTIME_SOURCE,
    type: 'lib',
  };
}
