import type { IRNode, KernConfig, KernTarget, ParseDiagnostic, ResolvedKernConfig } from '@kernlang/core';
import {
  clearTemplates,
  collectCoverageGaps,
  parseWithDiagnostics,
  registerTemplate,
  resolveConfig,
  writeCoverageGaps,
} from '@kernlang/core';
import { transpileExpress } from '@kernlang/express';
import { transpileFastAPI } from '@kernlang/fastapi';
import { transpileMCP } from '@kernlang/mcp';
import { transpile } from '@kernlang/native';
import { transpileNextjs, transpileTailwind, transpileWeb } from '@kernlang/react';
import { transpileInk, transpileTerminal } from '@kernlang/terminal';
import { transpileNuxt, transpileVue } from '@kernlang/vue';
import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'fs';
import { createJiti } from 'jiti';
import { basename, dirname, relative, resolve } from 'path';
import { transpileCliApp } from './transpiler-cli.js';

// ── Constants ────────────────────────────────────────────────────────────

export const GENERATED_HEADER = '// Generated by KERN — do not edit. Source: ';

// ── Arg parsing helpers ──────────────────────────────────────────────────

/** Get value of --flag=value */
export function parseFlag(args: string[], flag: string): string | undefined {
  return args.find((a) => a.startsWith(`${flag}=`))?.split('=')[1];
}

/** Get value of --flag=value OR --flag <value> (next positional arg) */
export function parseFlagOrNext(args: string[], flag: string): string | undefined {
  const eqArg = args.find((a) => a.startsWith(`${flag}=`));
  if (eqArg) return eqArg.split('=')[1];
  const idx = args.indexOf(flag);
  return idx !== -1 && idx + 1 < args.length ? args[idx + 1] : undefined;
}

/** Check if any of the given flags are present */
export function hasFlag(args: string[], ...flags: string[]): boolean {
  return flags.some((f) => args.includes(f));
}

// ── Parse helpers ────────────────────────────────────────────────────────

export function surfaceParseDiagnostics(diagnostics: ParseDiagnostic[], file?: string): void {
  if (diagnostics.length === 0) return;
  const prefix = file ? `${file}: ` : '';
  for (const diagnostic of diagnostics) {
    const tag = diagnostic.severity === 'error' ? 'ERROR' : diagnostic.severity === 'warning' ? 'WARN' : 'INFO';
    console.error(`  ${prefix}[${tag}] ${diagnostic.code}: ${diagnostic.message}`);
  }
}

export function parseAndSurface(source: string, file?: string): IRNode {
  const result = parseWithDiagnostics(source);
  surfaceParseDiagnostics(result.diagnostics, file);
  return result.root;
}

// ── File helpers ─────────────────────────────────────────────────────────

export function findNearestPackageJson(startDir: string): string | null {
  let dir = startDir;
  while (true) {
    const candidate = resolve(dir, 'package.json');
    if (existsSync(candidate)) return candidate;
    const parent = dirname(dir);
    if (parent === dir) return null;
    dir = parent;
  }
}

export function findKernFiles(dir: string, singleFile?: string): string[] {
  if (singleFile) return [resolve(dir, singleFile)];
  const files: string[] = [];
  function walk(d: string): void {
    for (const entry of readdirSync(d)) {
      const full = resolve(d, entry);
      const s = statSync(full);
      if (s.isDirectory() && !entry.startsWith('.') && entry !== 'node_modules' && entry !== 'dist') {
        walk(full);
      } else if (entry.endsWith('.kern')) {
        files.push(full);
      }
    }
  }
  walk(dir);
  return files;
}

export function collectTsFilesFlat(dirPath: string, recursive: boolean): string[] {
  const files: string[] = [];
  for (const entry of readdirSync(dirPath)) {
    const full = resolve(dirPath, entry);
    const s = statSync(full);
    if (s.isDirectory() && recursive && !entry.startsWith('.') && entry !== 'node_modules' && entry !== 'dist') {
      files.push(...collectTsFilesFlat(full, true));
    } else if (
      (entry.endsWith('.ts') || entry.endsWith('.tsx')) &&
      !entry.endsWith('.d.ts') &&
      !entry.endsWith('.test.ts')
    ) {
      files.push(full);
    } else if (entry.endsWith('.kern')) {
      files.push(full);
    } else if (entry.endsWith('.py') && !entry.startsWith('test_') && !entry.endsWith('_test.py')) {
      files.push(full);
    }
  }
  return files;
}

// ── Transpile dispatch ───────────────────────────────────────────────────

export function transpileForTarget(ast: IRNode, cfg: ResolvedKernConfig) {
  const target = cfg.target;
  return target === 'native'
    ? transpile(ast, cfg)
    : target === 'web'
      ? transpileWeb(ast, cfg)
      : target === 'tailwind'
        ? transpileTailwind(ast, cfg)
        : target === 'mcp'
          ? transpileMCP(ast, cfg)
          : target === 'express'
            ? transpileExpress(ast, cfg)
            : target === 'fastapi'
              ? transpileFastAPI(ast, cfg)
              : target === 'cli'
                ? transpileCliApp(ast, cfg)
                : target === 'terminal'
                  ? transpileTerminal(ast, cfg)
                  : target === 'ink'
                    ? transpileInk(ast, cfg)
                    : target === 'vue'
                      ? transpileVue(ast, cfg)
                      : target === 'nuxt'
                        ? transpileNuxt(ast, cfg)
                        : transpileNextjs(ast, cfg);
}

// ── Transpile + write ────────────────────────────────────────────────────

export function transpileAndWrite(
  file: string,
  cfg: ResolvedKernConfig,
  args: string[],
  outDirOverride?: string,
  inputBase?: string,
): void {
  const source = readFileSync(file, 'utf-8');
  const ast = parseAndSurface(source, file);
  const ext = file.endsWith('.kern') ? '.kern' : '.ir';
  const name = basename(file, ext);
  const target = cfg.target;
  const relSource = relative(process.cwd(), file);
  const header = `${GENERATED_HEADER + relSource}\n\n`;

  if (!args.includes('--no-gaps')) {
    const gaps = collectCoverageGaps(ast, file);
    if (gaps.length > 0) {
      writeCoverageGaps(gaps, resolve(process.cwd(), '.kern-gaps'));
    }
  }

  const result = transpileForTarget(ast, cfg);

  const relDir = inputBase ? relative(resolve(inputBase), dirname(file)) : '';
  const baseDir = outDirOverride ? resolve(resolve(outDirOverride), relDir) : dirname(file);
  const outDir = resolve(baseDir, cfg.output.outDir);
  mkdirSync(outDir, { recursive: true });

  if (result.artifacts && result.artifacts.length > 0 && cfg.structure !== 'flat') {
    for (const artifact of result.artifacts) {
      const artifactPath = resolve(outDir, artifact.path);
      mkdirSync(dirname(artifactPath), { recursive: true });
      writeFileSync(artifactPath, header + artifact.content);
    }
  } else {
    const outExt =
      target === 'fastapi'
        ? '.py'
        : target === 'vue' || target === 'nuxt'
          ? '.vue'
          : target === 'express' || target === 'cli' || target === 'terminal' || target === 'mcp'
            ? '.ts'
            : '.tsx';
    const resultWithFiles = result as { files?: Array<{ path: string; content: string }> };
    const outFileName =
      target === 'nextjs' && resultWithFiles.files && resultWithFiles.files.length > 0
        ? resultWithFiles.files[0].path
        : `${name}${outExt}`;
    const outFilePath = resolve(outDir, outFileName);
    mkdirSync(dirname(outFilePath), { recursive: true });
    writeFileSync(outFilePath, header + result.code);
    if (result.artifacts) {
      for (const artifact of result.artifacts) {
        const artifactPath = resolve(outDir, artifact.path);
        mkdirSync(dirname(artifactPath), { recursive: true });
        writeFileSync(artifactPath, header + artifact.content);
      }
    }
  }
}

// ── Config loading ───────────────────────────────────────────────────────

function autoDetectTarget(): KernTarget | null {
  const pkgPath = resolve(process.cwd(), 'package.json');
  if (!existsSync(pkgPath)) return null;
  try {
    const pkg = JSON.parse(readFileSync(pkgPath, 'utf-8'));
    const allDeps = { ...pkg.dependencies, ...pkg.devDependencies };
    if (allDeps.next) return 'nextjs';
    if (allDeps.nuxt) return 'nuxt' as any;
    if (allDeps.vue) return 'vue';
    if (allDeps['react-native']) return 'native';
    if (allDeps.fastapi) return 'fastapi';
    if (allDeps.flask || allDeps.django) {
      console.warn(
        `Warning: ${allDeps.flask ? 'Flask' : 'Django'} detected but no dedicated target — falling back to 'express' (generates TypeScript, not Python). Use --target=fastapi for Python output.`,
      );
      return 'express' as any;
    }
    if (allDeps.express || allDeps.fastify || allDeps.koa || allDeps.hono) return 'express';
    if (allDeps.tailwindcss && allDeps.react) return 'tailwind';
    if (allDeps.react) return 'web';
    return null;
  } catch {
    return null;
  }
}

export function loadConfig(): ResolvedKernConfig {
  const configPath = resolve(process.cwd(), 'kern.config.ts');
  if (existsSync(configPath)) {
    try {
      const jiti = createJiti(import.meta.url);
      const mod = jiti(configPath) as { default?: unknown };
      const userConfig = mod.default ?? mod;
      return resolveConfig(userConfig as Partial<KernConfig>);
    } catch (err) {
      console.error(`Warning: Failed to load kern.config.ts: ${(err as Error).message}`);
    }
  }

  const autoDetected = autoDetectTarget();
  return resolveConfig(autoDetected ? { target: autoDetected } : {});
}

export function loadTemplates(cfg: ResolvedKernConfig): void {
  clearTemplates();
  if (!cfg.templates || cfg.templates.length === 0) return;

  for (const templatePath of cfg.templates) {
    const resolved = resolve(process.cwd(), templatePath);
    if (!existsSync(resolved)) continue;

    const stat = statSync(resolved);
    const files: string[] = [];

    if (stat.isDirectory()) {
      for (const entry of readdirSync(resolved)) {
        if (entry.endsWith('.kern')) files.push(resolve(resolved, entry));
      }
    } else if (resolved.endsWith('.kern')) {
      files.push(resolved);
    }

    for (const file of files) {
      try {
        const source = readFileSync(file, 'utf-8');
        const ast = parseAndSurface(source, file);
        const nodes = ast.type === 'template' ? [ast] : (ast.children || []).filter((n) => n.type === 'template');
        for (const node of nodes) {
          registerTemplate(node, file);
        }
      } catch (err) {
        console.error(`  Warning: Failed to load template ${basename(file)}: ${(err as Error).message}`);
      }
    }
  }
}
