import type {
  IRNode,
  KernConfig,
  KernTarget,
  ParseDiagnostic,
  ResolvedKernConfig,
  SchemaViolation,
  ShadowAnalyzeOptions,
  ShadowDiagnostic,
} from '@kernlang/core';
import {
  analyzeShadow,
  COMMON_TEMPLATES,
  clearTemplates,
  collectCapabilityIslands,
  collectCoverageGaps,
  collectExternalBoundaries,
  collectSidecarManifests,
  detectKernStdlibUsage,
  detectReactHookDeps,
  detectTarget,
  expandTemplateNode,
  generateCoreNode,
  injectKernStdlibPreamble,
  injectKernStdlibPreambleIntoSFC,
  injectReactHookImports,
  isCoreNode,
  isTemplateNode,
  KERN_VERSION,
  kernStdlibPreamble,
  parseWithDiagnostics,
  registerTemplate,
  resolveConfig,
  sidecarManifestFromIsland,
  sourceComment,
  validateSchema,
  validateSemantics,
  writeCoverageGaps,
} from '@kernlang/core';
import { emitInterfaces, transpileExpress } from '@kernlang/express';
import { transpileGo } from '@kernlang/go';
import { transpileMCP } from '@kernlang/mcp';
import { transpile } from '@kernlang/native';
import { transpileFastAPI, transpilePython } from '@kernlang/python';
import { generateReactNode, isReactNode, transpileNextjs, transpileTailwind, transpileWeb } from '@kernlang/react';
import { transpileInk, transpileTerminal } from '@kernlang/terminal';
import { transpileNuxt, transpileVue } from '@kernlang/vue';
import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, unlinkSync, writeFileSync } from 'fs';
import { createJiti } from 'jiti';
import { basename, dirname, relative, resolve } from 'path';
import { transpileCliApp } from './transpiler-cli.js';

// ── Constants ────────────────────────────────────────────────────────────

export const GENERATED_HEADER = `// @generated by kern v${KERN_VERSION} — DO NOT EDIT. Source: `;
const PYTHON_GENERATED_HEADER = `# @generated by kern v${KERN_VERSION} — DO NOT EDIT. Source: `;

const SEMVER_PREFIX_PATTERN = /^(\d+)\.(\d+)\.(\d+)(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?/;
const STAMP_PATTERN = /^(?:\/\/|#)\s*@generated by kern v(\d+)\.(\d+)\.(\d+)/;
const GENERATED_HEADER_PATTERN =
  /^((?:\/\/|#)\s*@generated by kern) v\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?(.*)$/m;
const SOURCE_TRACE_PATTERN = /^\s*(?:\/\/|#) @kern-source: /m;
const TRACEABLE_NODE_TYPES = new Set([
  'action',
  'class',
  'config',
  'const',
  'enum',
  'error',
  'event',
  'fn',
  'hook',
  'interface',
  'machine',
  'mcp',
  'model',
  'repository',
  'screen',
  'service',
  'store',
  'tool',
  'type',
  'union',
]);

const PYTHON_STDLIB_PACKAGES = new Set([
  'abc',
  '__future__',
  'argparse',
  'array',
  'ast',
  'asyncio',
  'atexit',
  'audioop',
  'base64',
  'bdb',
  'binascii',
  'bisect',
  'builtins',
  'bz2',
  'calendar',
  'chunk',
  'cmath',
  'cmd',
  'code',
  'codecs',
  'colorsys',
  'collections',
  'concurrent',
  'configparser',
  'contextlib',
  'contextvars',
  'copy',
  'csv',
  'ctypes',
  'dataclasses',
  'datetime',
  'dbm',
  'decimal',
  'difflib',
  'dis',
  'doctest',
  'email',
  'encodings',
  'enum',
  'errno',
  'faulthandler',
  'filecmp',
  'fileinput',
  'fnmatch',
  'fractions',
  'ftplib',
  'functools',
  'gc',
  'getopt',
  'getpass',
  'gettext',
  'glob',
  'graphlib',
  'gzip',
  'hashlib',
  'heapq',
  'hmac',
  'html',
  'http',
  'imaplib',
  'importlib',
  'inspect',
  'io',
  'ipaddress',
  'itertools',
  'json',
  'keyword',
  'linecache',
  'locale',
  'logging',
  'lzma',
  'mailbox',
  'mailcap',
  'marshal',
  'math',
  'mimetypes',
  'mmap',
  'modulefinder',
  'multiprocessing',
  'netrc',
  'numbers',
  'opcode',
  'operator',
  'optparse',
  'os',
  'pathlib',
  'pdb',
  'pickle',
  'pickletools',
  'pkgutil',
  'platform',
  'plistlib',
  'poplib',
  'posixpath',
  'pprint',
  'profile',
  'pstats',
  'pty',
  'py_compile',
  'pydoc',
  'queue',
  'quopri',
  'random',
  're',
  'readline',
  'reprlib',
  'resource',
  'rlcompleter',
  'runpy',
  'sched',
  'secrets',
  'select',
  'selectors',
  'shelve',
  'shlex',
  'shutil',
  'signal',
  'site',
  'smtplib',
  'socket',
  'socketserver',
  'sqlite3',
  'ssl',
  'stat',
  'statistics',
  'string',
  'stringprep',
  'struct',
  'subprocess',
  'sys',
  'sysconfig',
  'tarfile',
  'tempfile',
  'termios',
  'textwrap',
  '_thread',
  'threading',
  'time',
  'timeit',
  'tkinter',
  'token',
  'tokenize',
  'tomllib',
  'trace',
  'traceback',
  'tracemalloc',
  'tty',
  'types',
  'typing',
  'unicodedata',
  'unittest',
  'urllib',
  'uuid',
  'venv',
  'warnings',
  'wave',
  'weakref',
  'webbrowser',
  'wsgiref',
  'xml',
  'xmlrpc',
  'zipapp',
  'zipfile',
  'zipimport',
  'zlib',
  'zoneinfo',
]);

function withGeneratedHeader(content: string, header: string): string {
  if (content.startsWith('#!')) {
    const newline = content.indexOf('\n');
    if (newline === -1) return `${content}\n${header}`;
    return `${content.slice(0, newline + 1)}${header}${content.slice(newline + 1)}`;
  }
  return `${header}${content}`;
}

function generatedHeaderForTarget(target: KernTarget, relSource: string): string {
  const prefix = target === 'fastapi' || target === 'python' ? PYTHON_GENERATED_HEADER : GENERATED_HEADER;
  return `${prefix + relSource}\n\n`;
}

function withCommentPrefix(comment: string, prefix: '//' | '#'): string {
  return prefix === '#' ? comment.replace(/^\/\//, '#') : comment;
}

function escapeRegex(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

interface SourceTracePoint {
  comment: string;
  name: string;
  nodeType: string;
}

function collectSourceTracePoints(
  ast: IRNode,
  sourceName: string,
  commentPrefix: '//' | '#' = '//',
): SourceTracePoint[] {
  const nodes = [ast, ...(ast.children || [])];
  return nodes
    .filter((node) => node.loc && TRACEABLE_NODE_TYPES.has(node.type) && typeof node.props?.name === 'string')
    .map((node) => ({
      comment: withCommentPrefix(sourceComment(node, sourceName), commentPrefix),
      name: node.props!.name as string,
      nodeType: node.type,
    }))
    .filter((point) => point.comment.length > 0);
}

function declarationPatterns(point: SourceTracePoint): RegExp[] {
  const name = escapeRegex(point.name);
  return [
    new RegExp(`^(\\s*)(?:export\\s+)?(?:default\\s+)?(?:async\\s+)?function\\s+${name}\\b`),
    new RegExp(`^(\\s*)(?:export\\s+)?(?:default\\s+)?class\\s+${name}\\b`),
    new RegExp(`^(\\s*)(?:export\\s+)?const\\s+${name}\\b`),
    new RegExp(`^(\\s*)(?:export\\s+)?let\\s+${name}\\b`),
    new RegExp(`^(\\s*)(?:export\\s+)?interface\\s+${name}\\b`),
    new RegExp(`^(\\s*)(?:export\\s+)?type\\s+${name}\\b`),
    new RegExp(`^(\\s*)(?:export\\s+)?enum\\s+${name}\\b`),
    new RegExp(`^(\\s*)(?:async\\s+)?def\\s+${name}\\b`),
    new RegExp(`^(\\s*)class\\s+${name}\\b`),
  ];
}

function sourceTraceInsertIndex(lines: string[]): number {
  let index = 0;
  if (lines[index]?.startsWith('#!')) index += 1;
  if (/^(?:\/\/|#) @generated by kern\b/.test(lines[index] ?? '')) {
    index += 1;
    if (lines[index] === '') index += 1;
  }
  return index;
}

function entryTracePoints(points: SourceTracePoint[]): SourceTracePoint[] {
  for (let index = points.length - 1; index >= 0; index -= 1) {
    if (points[index].nodeType === 'screen') return [points[index]];
  }
  return points.length > 0 ? [points[0]] : [];
}

function withSourceTraceComments(
  content: string,
  ast: IRNode,
  sourceName: string,
  options: { entry?: boolean; commentPrefix?: '//' | '#' } = {},
): string {
  if (content.trim().length === 0) return content;
  if (SOURCE_TRACE_PATTERN.test(content)) return content;

  const collectedPoints = collectSourceTracePoints(ast, sourceName, options.commentPrefix);
  const points = options.entry ? entryTracePoints(collectedPoints) : collectedPoints;
  if (points.length === 0) return content;

  const lines = content.split('\n');
  const unmatched: string[] = [];

  for (const point of points) {
    let inserted = false;
    const patterns = declarationPatterns(point);

    for (let index = 0; index < lines.length; index += 1) {
      if (!patterns.some((pattern) => pattern.test(lines[index]))) continue;
      lines.splice(index, 0, point.comment);
      inserted = true;
      break;
    }

    if (!inserted) unmatched.push(point.comment);
  }

  if (unmatched.length > 0) {
    lines.splice(sourceTraceInsertIndex(lines), 0, ...unmatched, '');
  }

  return lines.join('\n');
}

/** Parse a [major, minor, patch] tuple from a generated-header line, or null if absent. */
function parseStampedVersion(file: string): [number, number, number] | null {
  let candidateLines: string[];
  try {
    const buf = readFileSync(file, 'utf-8');
    candidateLines = buf.split('\n').slice(0, 2);
  } catch {
    return null;
  }

  for (const line of candidateLines) {
    const match = line.match(STAMP_PATTERN);
    if (match) return [Number(match[1]), Number(match[2]), Number(match[3])];
  }

  return null;
}

export function parseCompilerVersion(version: string): [number, number, number] | null {
  const match = version.match(SEMVER_PREFIX_PATTERN);
  if (!match) return null;
  return [Number(match[1]), Number(match[2]), Number(match[3])];
}

function compareSemver(a: [number, number, number], b: [number, number, number]): number {
  for (let i = 0; i < 3; i++) {
    if (a[i] !== b[i]) return a[i] - b[i];
  }
  return 0;
}

function normalizeGeneratedHeaderVersion(content: string): string {
  return content.replace(GENERATED_HEADER_PATTERN, '$1 v<version>$2');
}

function differsOnlyByGeneratedHeaderVersion(existing: string, next: string): boolean {
  return existing !== next && normalizeGeneratedHeaderVersion(existing) === normalizeGeneratedHeaderVersion(next);
}

/**
 * Check the existing output file's @generated stamp against the current compiler version.
 * Emits a warning when the stamp is newer (downgrade) or older by a minor/major (drift).
 * Stays silent on patch-level drift and on first compile.
 */
export function checkVersionDrift(outFilePath: string, sourceFile: string): void {
  if (!existsSync(outFilePath)) return;
  const stamped = parseStampedVersion(outFilePath);
  if (!stamped) return;

  const current = parseCompilerVersion(KERN_VERSION);
  if (!current) return;

  const cmp = compareSemver(stamped, current);
  if (cmp === 0) return;

  if (cmp > 0) {
    console.warn(
      `  WARN kern-compiler-drift: ${sourceFile}: existing output was generated by kern v${stamped.join('.')}, but the active compiler is v${KERN_VERSION}. Re-compiling with an OLDER compiler may regress codegen features.`,
    );
    return;
  }

  // stamped is older than current
  if (stamped[0] !== current[0] || stamped[1] !== current[1]) {
    console.warn(
      `  INFO kern-compiler-drift: ${sourceFile}: existing output was generated by kern v${stamped.join('.')}, current compiler is v${KERN_VERSION}. Output will be re-generated.`,
    );
  }
}

function writeGeneratedFileSync(outFilePath: string, content: string, sourceFile: string): void {
  if (existsSync(outFilePath)) {
    const existing = readFileSync(outFilePath, 'utf-8');
    if (existing === content || differsOnlyByGeneratedHeaderVersion(existing, content)) return;
  }

  checkVersionDrift(outFilePath, sourceFile);
  writeFileSync(outFilePath, content);
}

export function writeSidecarInstallFiles(ast: IRNode, outDir: string): void {
  writeSidecarInstallFilesForAsts([ast], outDir);
}

interface SidecarInstallFileOptions {
  sidecarIslandsOnly?: boolean;
}

function sidecarManifestsForInstall(ast: IRNode, options?: SidecarInstallFileOptions) {
  if (options?.sidecarIslandsOnly === true) {
    return collectCapabilityIslands(ast)
      .map((island) => sidecarManifestFromIsland(island))
      .filter((manifest) => manifest !== null);
  }
  return collectSidecarManifests(ast);
}

function pythonRequirementLine(packageName: string, version?: string): string | undefined {
  const root = packageName.split('.')[0];
  if (!root || PYTHON_STDLIB_PACKAGES.has(root)) return undefined;
  return version ? `${packageName}==${version}` : packageName;
}

export function writeSidecarInstallFilesForAsts(
  asts: Iterable<IRNode>,
  outDir: string,
  options?: SidecarInstallFileOptions,
): void {
  const manifests = [...asts].flatMap((ast) => sidecarManifestsForInstall(ast, options));
  const sidecarsPath = resolve(outDir, 'kern-sidecars.json');
  const requirementsPath = resolve(outDir, 'kern-sidecar-requirements.txt');
  if (manifests.length === 0) {
    if (existsSync(sidecarsPath)) unlinkSync(sidecarsPath);
    if (existsSync(requirementsPath)) unlinkSync(requirementsPath);
    return;
  }
  writeFileSync(sidecarsPath, `${JSON.stringify({ version: 1, sidecars: manifests }, null, 2)}\n`);

  const requirements = new Set<string>();
  for (const manifest of manifests) {
    for (const sidecarPackage of manifest.packages) {
      if (sidecarPackage.registry !== 'pypi') continue;
      const requirement = pythonRequirementLine(sidecarPackage.package, sidecarPackage.version);
      if (requirement) requirements.add(requirement);
    }
  }
  if (requirements.size > 0) {
    writeFileSync(requirementsPath, `${[...requirements].sort().join('\n')}\n`);
  } else if (existsSync(requirementsPath)) {
    unlinkSync(requirementsPath);
  }
}

export function writeFastApiPythonInstallFilesForAsts(asts: Iterable<IRNode>, outDir: string): void {
  const requirementsPath = resolve(outDir, 'kern-python-requirements.txt');
  const requirements = new Set<string>();
  for (const ast of asts) {
    for (const boundary of collectExternalBoundaries(ast)) {
      if (boundary.registry !== 'pypi') continue;
      if (boundary.targetFamily !== 'python' && boundary.targetFamily !== 'all') continue;
      if (boundary.island) continue;
      const requirement = pythonRequirementLine(boundary.package, boundary.version);
      if (requirement) requirements.add(requirement);
    }
  }
  if (requirements.size > 0) {
    mkdirSync(outDir, { recursive: true });
    writeFileSync(requirementsPath, `${[...requirements].sort().join('\n')}\n`);
  } else if (existsSync(requirementsPath)) {
    unlinkSync(requirementsPath);
  }
}

type TranspileAndWriteOptions = import('@kernlang/core').ParseOptions & {
  fastApiEntryModules?: string[];
  fastApiModuleNameByFile?: Record<string, string>;
  fastApiModulePathByFile?: Record<string, string>;
  outputBaseName?: string;
  outputRelDir?: string;
  writeSidecarInstallFiles?: boolean;
};

// ── Arg parsing helpers ──────────────────────────────────────────────────

/** Get value of --flag=value */
export function parseFlag(args: string[], flag: string): string | undefined {
  return args.find((a) => a.startsWith(`${flag}=`))?.split('=')[1];
}

/** Get value of --flag=value OR --flag <value> (next positional arg) */
export function parseFlagOrNext(args: string[], flag: string): string | undefined {
  const eqArg = args.find((a) => a.startsWith(`${flag}=`));
  if (eqArg) return eqArg.split('=')[1];
  const idx = args.indexOf(flag);
  return idx !== -1 && idx + 1 < args.length ? args[idx + 1] : undefined;
}

/** Check if any of the given flags are present */
export function hasFlag(args: string[], ...flags: string[]): boolean {
  return flags.some((f) => args.includes(f));
}

// ── Parse helpers ────────────────────────────────────────────────────────

export function surfaceParseDiagnostics(
  diagnostics: ParseDiagnostic[],
  file?: string,
): { errors: number; warnings: number } {
  if (diagnostics.length === 0) return { errors: 0, warnings: 0 };
  const prefix = file ? `${file}: ` : '';
  let errors = 0;
  let warnings = 0;
  for (const diagnostic of diagnostics) {
    // Slice 5a: native-eligibility hints fire on every raw handler whose
    // body could opt in to lang="kern". They're surfaced via the API for
    // IDE integrations and the future `kern migrate native-handlers` CLI,
    // but printing them on every `kern compile` would flood CI logs and
    // user output. Skip from the default print path; dedicated commands
    // (gaps, migrate, review) can opt to surface them explicitly.
    if (diagnostic.code === 'NATIVE_KERN_ELIGIBLE') continue;
    const tag = diagnostic.severity === 'error' ? 'ERROR' : diagnostic.severity === 'warning' ? 'WARN' : 'INFO';
    console.error(`  ${prefix}[${tag}] ${diagnostic.code}: ${diagnostic.message}`);
    if (diagnostic.severity === 'error') errors++;
    else if (diagnostic.severity === 'warning') warnings++;
  }
  return { errors, warnings };
}

function validationViolations(root: IRNode): SchemaViolation[] {
  return [
    ...validateSchema(root),
    ...validateSemantics(root).map((sv) => ({
      nodeType: sv.nodeType,
      message: `[${sv.rule}] ${sv.message}`,
      line: sv.line,
      col: sv.col,
    })),
  ];
}

export function surfaceValidationDiagnostics(root: IRNode, file?: string): { errors: number; warnings: number } {
  const violations = validationViolations(root);
  if (violations.length === 0) return { errors: 0, warnings: 0 };
  const prefix = file ? `${file}: ` : '';
  for (const violation of violations) {
    const where = violation.line != null ? `:${violation.line}${violation.col != null ? `:${violation.col}` : ''}` : '';
    console.error(`  ${prefix}[ERROR] VALIDATION${where}: ${violation.message}`);
  }
  return { errors: violations.length, warnings: 0 };
}

export function parseAndSurface(
  source: string,
  file?: string,
  options?: import('@kernlang/core').ParseOptions,
  surfaceValidation = false,
): IRNode {
  const result = parseWithDiagnostics(source, undefined, options);
  surfaceParseDiagnostics(result.diagnostics, file);
  if (surfaceValidation) surfaceValidationDiagnostics(result.root, file);
  return result.root;
}

// ── JSON Diagnostics (LLM consumption) ──────────────────────────────────

export interface FileDiagnosticsJSON {
  file: string;
  success: boolean;
  diagnostics: ParseDiagnostic[];
  schemaViolations: SchemaViolation[];
  shadowDiagnostics?: ShadowDiagnostic[];
  /** Islands are the owner view; externalBoundaries includes the same child imports with inherited island metadata. */
  capabilityIslands: import('@kernlang/core').CapabilityIsland[];
  sidecarManifests: import('@kernlang/core').SidecarManifest[];
  externalBoundaries: import('@kernlang/core').ExternalBoundary[];
}

/** Parse a .kern file and return structured diagnostics as JSON-serializable object. */
export function parseWithJSONDiagnostics(
  source: string,
  file: string,
  options?: import('@kernlang/core').ParseOptions,
): { root: IRNode; json: FileDiagnosticsJSON } {
  const result = parseWithDiagnostics(source, undefined, options);
  const schemaViolations = validationViolations(result.root);
  const hasErrors = result.diagnostics.some((d) => d.severity === 'error') || schemaViolations.length > 0;

  return {
    root: result.root,
    json: {
      file,
      success: !hasErrors,
      diagnostics: result.diagnostics,
      schemaViolations,
      // Best-effort even when parsing/schema validation reports errors, so
      // review tools can still show declared foreign boundaries near failures.
      capabilityIslands: collectCapabilityIslands(result.root),
      sidecarManifests: collectSidecarManifests(result.root),
      externalBoundaries: collectExternalBoundaries(result.root),
    },
  };
}

// ── Output extension helper ─────────────────────────────────────────────

/** Get the output file extension for a given target. Deduplicates the ternary chain. */
export function getOutputExtension(target: KernTarget): string {
  switch (target) {
    case 'fastapi':
    case 'python':
      return '.py';
    case 'go':
      return '.go';
    case 'vue':
    case 'nuxt':
      return '.vue';
    case 'lib':
    case 'express':
    case 'cli':
    case 'terminal':
    case 'mcp':
      return '.ts';
    default:
      return '.tsx';
  }
}

const PYTHON_KEYWORDS = new Set([
  'False',
  'None',
  'True',
  'and',
  'as',
  'assert',
  'async',
  'await',
  'break',
  'class',
  'continue',
  'def',
  'del',
  'elif',
  'else',
  'except',
  'finally',
  'for',
  'from',
  'global',
  'if',
  'import',
  'in',
  'is',
  'lambda',
  'nonlocal',
  'not',
  'or',
  'pass',
  'raise',
  'return',
  'try',
  'while',
  'with',
  'yield',
]);

// Keep in sync with top-level FastAPI generated artifact names.
const PYTHON_GENERATED_MODULE_NAMES = new Set(['alembic', 'auth', 'middleware', 'routes', 'ws']);

export function pythonModuleName(name: string): string {
  const sanitized = name.replace(/[^A-Za-z0-9_]/g, '_').replace(/^([0-9])/, '_$1');
  const moduleName = sanitized.length > 0 ? sanitized : 'main';
  return PYTHON_KEYWORDS.has(moduleName) ||
    PYTHON_STDLIB_PACKAGES.has(moduleName) ||
    PYTHON_GENERATED_MODULE_NAMES.has(moduleName) ||
    /^__.*__$/.test(moduleName)
    ? `${moduleName}_`
    : moduleName;
}

export function outputBaseNameForTarget(name: string, target: KernTarget): string {
  return target === 'fastapi' || target === 'python' ? pythonModuleName(name) : name;
}

export function withFastApiEntryModules(cfg: ResolvedKernConfig, entryModules: string[]): ResolvedKernConfig {
  if (cfg.target !== 'fastapi') return cfg;
  const modules = [...new Set(entryModules.filter((moduleName) => moduleName.length > 0))];
  return {
    ...cfg,
    fastapi: {
      ...cfg.fastapi,
      entryModules: modules,
    },
  } as ResolvedKernConfig;
}

export function withFastApiModuleMap(
  cfg: ResolvedKernConfig,
  sourceFile: string,
  moduleNameByFile?: Record<string, string>,
  modulePathByFile?: Record<string, string>,
): ResolvedKernConfig {
  if (cfg.target !== 'fastapi' || (!moduleNameByFile && !modulePathByFile)) return cfg;
  return {
    ...cfg,
    fastapi: {
      ...cfg.fastapi,
      sourceFile,
      ...(moduleNameByFile ? { moduleNameByFile } : {}),
      ...(modulePathByFile ? { modulePathByFile } : {}),
    },
  } as ResolvedKernConfig;
}

// ── Export extraction ───────────────────────────────────────────────────

/** Extract exported symbol names from generated TypeScript lines, distinguishing type-only exports. */
export function extractExportsFromLines(lines: string[]): { name: string; typeOnly: boolean }[] {
  const exports: { name: string; typeOnly: boolean }[] = [];
  // `const\s+enum` must come BEFORE the bare `const` branch — otherwise the regex
  // matches `export const` and captures `enum` as the identifier instead of `Flag`
  // for `export const enum Flag { ... }` (slice 2b regression caught by Codex).
  const re = /^export\s+(?:async\s+)?(?:function\*?|class|const\s+enum|const|enum|abstract\s+class)\s+(\w+)/;
  const typeRe = /^export\s+(?:interface|type)\s+(\w+)/;
  // Slice 2e — function overloads + impl share the same `export function name`
  // prefix; without dedup the barrel emits `export { add, add, add }` (TS error).
  // Dedupe by (name, typeOnly) — TS allows a value and a type with the same
  // name (namespace merging) but not two values.
  const seen = new Set<string>();
  const key = (name: string, typeOnly: boolean) => `${typeOnly ? 't' : 'v'}:${name}`;
  for (const line of lines) {
    const m = line.match(re);
    if (m) {
      const k = key(m[1], false);
      if (seen.has(k)) continue;
      seen.add(k);
      exports.push({ name: m[1], typeOnly: false });
      continue;
    }
    const tm = line.match(typeRe);
    if (tm) {
      const k = key(tm[1], true);
      if (seen.has(k)) continue;
      seen.add(k);
      exports.push({ name: tm[1], typeOnly: true });
    }
  }
  return exports;
}

// ── Barrel & Facade generation ──────────────────────────────────────────

export interface BarrelEntry {
  moduleName: string;
  exports: { name: string; typeOnly: boolean }[];
}

/** Scan output directory for .ts/.tsx files and build barrel entries from their exports. */
export function scanOutputForBarrelEntries(outDir: string): BarrelEntry[] {
  if (!existsSync(outDir)) return [];
  const entries: BarrelEntry[] = [];

  function scan(dir: string): void {
    for (const file of readdirSync(dir)) {
      const full = resolve(dir, file);
      if (statSync(full).isDirectory()) {
        scan(full);
        continue;
      }
      if (file === 'index.ts' || file === '_barrel.ts') continue;
      if (!file.endsWith('.ts') && !file.endsWith('.tsx')) continue;
      const content = readFileSync(full, 'utf-8');
      const exports = extractExportsFromLines(content.split('\n'));
      if (exports.length > 0) {
        // Use path relative to outDir as module name so barrel imports resolve
        const relPath = relative(outDir, full).replace(/\.tsx?$/, '');
        entries.push({ moduleName: relPath, exports });
      }
    }
  }

  scan(outDir);
  return entries;
}

/** Generate a barrel index file that re-exports from all compiled modules. */
export function generateBarrelFile(outDir: string, entries: BarrelEntry[]): void {
  if (entries.length === 0) return;
  const hasIndexKern = entries.some((e) => e.moduleName === 'index');
  const barrelName = hasIndexKern ? '_barrel.ts' : 'index.ts';
  const barrelLines = ['// @generated by kern — DO NOT EDIT.', ''];
  for (const entry of entries) {
    const valueExports = entry.exports.filter((e) => !e.typeOnly).map((e) => e.name);
    const typeExports = entry.exports.filter((e) => e.typeOnly).map((e) => e.name);
    if (valueExports.length > 0) {
      barrelLines.push(`export { ${valueExports.join(', ')} } from './${entry.moduleName}.js';`);
    }
    if (typeExports.length > 0) {
      barrelLines.push(`export type { ${typeExports.join(', ')} } from './${entry.moduleName}.js';`);
    }
  }
  barrelLines.push('');
  const barrelFile = resolve(outDir, barrelName);
  writeFileSync(barrelFile, barrelLines.join('\n'));
  const totalExports = entries.reduce((n, e) => n + e.exports.length, 0);
  console.log(`  barrel → ${barrelName} (${totalExports} exports)`);
}

/** Generate facade re-export files and an index.ts that re-exports from facades. */
export function generateFacadeFiles(
  outDir: string,
  facadesDirOverride: string | undefined,
  entries: BarrelEntry[],
): void {
  if (entries.length === 0) return;
  const facadesDirPath = resolve(facadesDirOverride || resolve(dirname(outDir), 'src'));
  mkdirSync(facadesDirPath, { recursive: true });
  const relToGenerated = relative(facadesDirPath, outDir);
  const facadeFiles: string[] = [];

  for (const entry of entries) {
    const facadeFile = resolve(facadesDirPath, `${entry.moduleName}.ts`);
    if (existsSync(facadeFile)) continue;
    // Create parent directories for nested module paths (e.g. routes/get-users)
    mkdirSync(dirname(facadeFile), { recursive: true });
    const relPath = `${relToGenerated}/${entry.moduleName}.js`;
    writeFileSync(facadeFile, `export * from '${relPath}';\n`);
    facadeFiles.push(entry.moduleName);
  }

  if (facadeFiles.length > 0) {
    console.log(`  facades → ${facadesDirPath} (${facadeFiles.length} files)`);
  }

  const parentDir = dirname(outDir);
  const relToFacades = relative(parentDir, facadesDirPath);
  const indexLines = ['// @generated by kern — DO NOT EDIT.', ''];
  for (const entry of entries) {
    indexLines.push(`export * from './${relToFacades}/${entry.moduleName}.js';`);
  }
  indexLines.push('');
  const indexFile = resolve(parentDir, 'index.ts');
  if (!existsSync(indexFile) || readFileSync(indexFile, 'utf-8').startsWith('// @generated by kern')) {
    writeFileSync(indexFile, indexLines.join('\n'));
    console.log(`  facades index → ${relative(process.cwd(), indexFile)}`);
  } else {
    console.log(`  facades index → skipped (${relative(process.cwd(), indexFile)} already exists)`);
  }
}

// ── File helpers ─────────────────────────────────────────────────────────

export function findNearestPackageJson(startDir: string): string | null {
  let dir = startDir;
  while (true) {
    const candidate = resolve(dir, 'package.json');
    if (existsSync(candidate)) return candidate;
    const parent = dirname(dir);
    if (parent === dir) return null;
    dir = parent;
  }
}

/** Load .kernignore patterns from the given directory (or nearest parent). */
function loadKernIgnore(startDir: string): string[] {
  let dir = startDir;
  while (true) {
    const candidate = resolve(dir, '.kernignore');
    if (existsSync(candidate)) {
      return readFileSync(candidate, 'utf-8')
        .split('\n')
        .map((l) => l.trim())
        .filter((l) => l && !l.startsWith('#'));
    }
    const parent = dirname(dir);
    if (parent === dir) return [];
    dir = parent;
  }
}

/** Escape regex special characters except * which is used as glob wildcard. */
function escapeRegexExceptStar(s: string): string {
  return s.replace(/[.+?^${}()|[\]\\]/g, '\\$&');
}

/** Check if a path matches any of the ignore patterns (simple glob-like matching). */
function isIgnored(filePath: string, baseDir: string, patterns: string[]): boolean {
  const rel = relative(baseDir, filePath);
  return patterns.some((pattern) => {
    if (pattern.endsWith('/')) return rel.startsWith(pattern) || rel.includes(`/${pattern}`);
    if (pattern.includes('*')) {
      // Escape regex chars, then convert * to .* and ** to match across directories
      const escaped = escapeRegexExceptStar(pattern)
        .replace(/\*\*/g, '@@GLOBSTAR@@')
        .replace(/\*/g, '[^/]*')
        .replace(/@@GLOBSTAR@@/g, '.*');
      const regex = new RegExp(`^${escaped}$`);
      return regex.test(rel) || regex.test(basename(filePath));
    }
    return rel === pattern || basename(filePath) === pattern;
  });
}

export function findKernFiles(dir: string, singleFile?: string): string[] {
  if (singleFile) return [resolve(dir, singleFile)];
  const ignorePatterns = loadKernIgnore(dir);
  const files: string[] = [];
  function walk(d: string): void {
    for (const entry of readdirSync(d)) {
      const full = resolve(d, entry);
      const s = statSync(full);
      if (s.isDirectory() && !entry.startsWith('.') && entry !== 'node_modules' && entry !== 'dist') {
        walk(full);
      } else if (entry.endsWith('.kern')) {
        if (ignorePatterns.length === 0 || !isIgnored(full, dir, ignorePatterns)) {
          files.push(full);
        }
      }
    }
  }
  walk(dir);
  return files;
}

export function collectTsFilesFlat(dirPath: string, recursive: boolean): string[] {
  const files: string[] = [];
  for (const entry of readdirSync(dirPath)) {
    const full = resolve(dirPath, entry);
    const s = statSync(full);
    if (
      s.isDirectory() &&
      recursive &&
      !entry.startsWith('.') &&
      entry !== 'node_modules' &&
      entry !== 'dist' &&
      entry !== 'out' &&
      entry !== '__pycache__' &&
      entry !== 'venv'
    ) {
      files.push(...collectTsFilesFlat(full, true));
    } else if (
      s.isFile() &&
      (entry.endsWith('.ts') || entry.endsWith('.tsx')) &&
      !entry.endsWith('.d.ts') &&
      !entry.endsWith('.test.ts')
    ) {
      files.push(full);
    } else if (s.isFile() && entry.endsWith('.kern')) {
      files.push(full);
    } else if (s.isFile() && entry.endsWith('.py') && !entry.startsWith('test_') && !entry.endsWith('_test.py')) {
      files.push(full);
    }
  }
  return files;
}

// ── Library passthrough transpiler ───────────────────────────────────────

/** Plain TypeScript output — no framework wrapper, no JSX, no scaffold. */
function transpileLib(ast: IRNode, _cfg: ResolvedKernConfig): import('@kernlang/core').TranspileResult {
  if (_cfg.emit === 'types') {
    const { code } = emitInterfaces(ast, { emit: 'types', target: 'lib' });
    return { code, sourceMap: [], irTokenCount: 0, tsTokenCount: 0, tokenReduction: 0 };
  }

  const lines: string[] = [];

  function processNode(node: IRNode): void {
    if (isReactNode(node.type)) {
      lines.push(...generateReactNode(node));
      lines.push('');
    } else if (isCoreNode(node.type)) {
      lines.push(...generateCoreNode(node));
      lines.push('');
    } else if (isTemplateNode(node.type)) {
      lines.push(...expandTemplateNode(node));
      lines.push('');
    }
  }

  processNode(ast);
  if (ast.type !== 'module' && ast.children) {
    for (const child of ast.children) {
      processNode(child);
    }
  }

  const code = lines.join('\n');
  return { code, sourceMap: [], irTokenCount: 0, tsTokenCount: 0, tokenReduction: 0 };
}

/** Slice 4 layer 2 — apply the Result / Option preamble post-transpile.
 *
 *  Lifted from `transpileLib` so every TS-family target picks up the compact
 *  form without each transpiler needing its own integration. FastAPI is
 *  excluded (Python).
 *
 *  Slice 4 follow-up — Vue / Nuxt SFC outputs route through
 *  `injectKernStdlibPreambleIntoSFC`, which inserts the preamble INSIDE
 *  the `<script setup lang="ts">` block instead of before it. The earlier
 *  blanket pre-injection broke `.vue` parse because raw `type Result<…>`
 *  text appeared ahead of the SFC. Plain TS-family targets continue to
 *  use `injectKernStdlibPreamble` (which knows about `'use client'`,
 *  hashbangs, and JSDoc).
 *
 *  Multi-artifact targets (express routes, structured Next.js, etc.) get the
 *  preamble injected into every artifact whose path ends in `.ts` / `.tsx`
 *  / `.mts` / `.cts`, since each route file independently references types
 *  in its handlers. Structured Vue / Nuxt artifacts use the SFC injector
 *  for `.vue` files. */
const TS_FAMILY_TARGETS: ReadonlySet<KernTarget> = new Set<KernTarget>([
  'lib',
  'native',
  'web',
  'tailwind',
  'mcp',
  'express',
  'cli',
  'terminal',
  'ink',
  'nextjs',
]);

const SFC_TARGETS: ReadonlySet<KernTarget> = new Set<KernTarget>(['vue', 'nuxt']);

function isTsArtifactPath(path: string): boolean {
  return path.endsWith('.ts') || path.endsWith('.tsx') || path.endsWith('.mts') || path.endsWith('.cts');
}

function isSfcArtifactPath(path: string): boolean {
  return path.endsWith('.vue');
}

function applyKernStdlibPreamble(
  ast: IRNode,
  target: KernTarget,
  result: import('@kernlang/core').TranspileResult,
): import('@kernlang/core').TranspileResult {
  const isSfc = SFC_TARGETS.has(target);
  if (!TS_FAMILY_TARGETS.has(target) && !isSfc) return result;

  const usage = detectKernStdlibUsage(ast);
  const preamble = kernStdlibPreamble(usage);
  if (preamble.length === 0) return result;

  const inject = isSfc ? injectKernStdlibPreambleIntoSFC : injectKernStdlibPreamble;
  const updatedCode = inject(result.code, preamble);
  const updatedArtifacts = result.artifacts?.map((art) => {
    if (isSfcArtifactPath(art.path)) {
      return { ...art, content: injectKernStdlibPreambleIntoSFC(art.content, preamble) };
    }
    if (isTsArtifactPath(art.path)) {
      return { ...art, content: injectKernStdlibPreamble(art.content, preamble) };
    }
    return art;
  });

  return {
    ...result,
    code: updatedCode,
    ...(updatedArtifacts ? { artifacts: updatedArtifacts } : {}),
  };
}

// ── Transpile dispatch ───────────────────────────────────────────────────

function dispatchTranspile(target: KernTarget, ast: IRNode, cfg: ResolvedKernConfig) {
  return target === 'lib'
    ? transpileLib(ast, cfg)
    : target === 'native'
      ? transpile(ast, cfg)
      : target === 'web'
        ? transpileWeb(ast, cfg)
        : target === 'tailwind'
          ? transpileTailwind(ast, cfg)
          : target === 'mcp'
            ? transpileMCP(ast, cfg)
            : target === 'express'
              ? transpileExpress(ast, cfg)
              : target === 'go'
                ? transpileGo(ast, cfg)
                : target === 'fastapi'
                  ? transpileFastAPI(ast, cfg)
                  : target === 'python'
                    ? transpilePython(ast, cfg)
                    : target === 'cli'
                      ? transpileCliApp(ast, cfg)
                      : target === 'terminal'
                        ? transpileTerminal(ast, cfg)
                        : target === 'ink'
                          ? transpileInk(ast, cfg)
                          : target === 'vue'
                            ? transpileVue(ast, cfg)
                            : target === 'nuxt'
                              ? transpileNuxt(ast, cfg)
                              : transpileNextjs(ast, cfg);
}

export function transpileForTarget(ast: IRNode, cfg: ResolvedKernConfig) {
  const target = cfg.target === 'auto' ? detectTarget(ast) : cfg.target;
  const result = dispatchTranspile(target, ast, cfg);
  // Slice 4 layer 2 — auto-emit Result / Option type aliases for every
  // TS-family target. Single integration point so target transpilers don't
  // each need their own preamble plumbing.
  const withPreamble = applyKernStdlibPreamble(ast, target, result);
  // Slice C-cell-v4 — auto-emit `import { useState } from 'react'` for
  // body-statement `cell` usage. Runs after the stdlib preamble so the
  // hook import lands in the same import region the preamble's directive
  // skip already established.
  return applyReactHookImports(ast, target, withPreamble);
}

function applyReactHookImports(
  ast: IRNode,
  target: KernTarget,
  result: import('@kernlang/core').TranspileResult,
): import('@kernlang/core').TranspileResult {
  if (!TS_FAMILY_TARGETS.has(target)) return result;
  const deps = detectReactHookDeps(ast);
  if (deps.size === 0) return result;
  const updatedCode = injectReactHookImports(result.code, deps);
  const updatedArtifacts = result.artifacts?.map((art) => {
    if (isTsArtifactPath(art.path)) {
      return { ...art, content: injectReactHookImports(art.content, deps) };
    }
    return art;
  });
  return {
    ...result,
    code: updatedCode,
    ...(updatedArtifacts ? { artifacts: updatedArtifacts } : {}),
  };
}

// ── Transpile + write ────────────────────────────────────────────────────

export function transpileAndWrite(
  file: string,
  cfg: ResolvedKernConfig,
  args: string[],
  outDirOverride?: string,
  inputBase?: string,
  options?: TranspileAndWriteOptions,
): void {
  const source = readFileSync(file, 'utf-8');
  const ast = parseAndSurface(source, file, options);
  const ext = file.endsWith('.kern') ? '.kern' : '.ir';
  const name = basename(file, ext);
  const sourceName = basename(file, ext);
  const relSource = relative(process.cwd(), file);

  if (!args.includes('--no-gaps')) {
    const gaps = collectCoverageGaps(ast, file);
    if (gaps.length > 0) {
      writeCoverageGaps(gaps, resolve(process.cwd(), '.kern-gaps'));
    }
  }

  // Resolve auto target per-file from AST content
  const effectiveCfg = cfg.target === 'auto' ? { ...cfg, target: detectTarget(ast) } : cfg;
  const target = effectiveCfg.target;
  const plannedOutBaseName =
    target === 'fastapi' ? (options?.outputBaseName ?? options?.fastApiModuleNameByFile?.[resolve(file)]) : undefined;
  const outBaseName =
    target === 'fastapi' && plannedOutBaseName ? plannedOutBaseName : outputBaseNameForTarget(name, target);
  const configuredFastApiEntryModules = options?.fastApiEntryModules?.filter((moduleName) => moduleName.length > 0);
  const fastApiEntryModules =
    target === 'fastapi' && configuredFastApiEntryModules && configuredFastApiEntryModules.length > 0
      ? configuredFastApiEntryModules
      : [outBaseName];
  const transpileCfg = withFastApiModuleMap(
    withFastApiEntryModules(effectiveCfg, fastApiEntryModules),
    resolve(file),
    options?.fastApiModuleNameByFile,
    options?.fastApiModulePathByFile,
  );
  const commentPrefix = target === 'fastapi' || target === 'python' ? '#' : '//';
  const header = generatedHeaderForTarget(target, relSource);
  const result = transpileForTarget(ast, transpileCfg);

  const fastApiOutputRelDir = target === 'fastapi' ? options?.outputRelDir : undefined;
  const usesFastApiOutputRelDir = fastApiOutputRelDir !== undefined;
  const relDir = usesFastApiOutputRelDir
    ? fastApiOutputRelDir
    : inputBase
      ? relative(resolve(inputBase), dirname(file))
      : '';
  const baseDir = outDirOverride ? resolve(resolve(outDirOverride), relDir) : dirname(file);
  const outDir =
    usesFastApiOutputRelDir && outDirOverride
      ? resolve(resolve(outDirOverride), cfg.output.outDir, relDir)
      : resolve(baseDir, cfg.output.outDir);
  mkdirSync(outDir, { recursive: true });
  if (options?.writeSidecarInstallFiles !== false) writeSidecarInstallFiles(ast, outDir);

  if (
    result.artifacts &&
    result.artifacts.length > 0 &&
    (cfg.structure !== 'flat' || target === 'go') &&
    target !== 'fastapi'
  ) {
    for (const artifact of result.artifacts) {
      const artifactPath = resolve(outDir, artifact.path);
      mkdirSync(dirname(artifactPath), { recursive: true });
      const tracedContent = withSourceTraceComments(artifact.content, ast, sourceName, {
        entry: artifact.type === 'entry',
        commentPrefix,
      });
      writeGeneratedFileSync(artifactPath, withGeneratedHeader(tracedContent, header), relSource);
    }
  } else {
    const outExt =
      target === 'fastapi' || target === 'python'
        ? '.py'
        : target === 'vue' || target === 'nuxt'
          ? '.vue'
          : target === 'go'
            ? '.go'
            : target === 'lib' || target === 'express' || target === 'cli' || target === 'terminal' || target === 'mcp'
              ? '.ts'
              : '.tsx';
    const resultWithFiles = result as { files?: Array<{ path: string; content: string }> };
    const outFileName =
      target === 'nextjs' && resultWithFiles.files && resultWithFiles.files.length > 0
        ? resultWithFiles.files[0].path
        : `${outBaseName}${outExt}`;
    const outFilePath = resolve(outDir, outFileName);
    mkdirSync(dirname(outFilePath), { recursive: true });
    writeGeneratedFileSync(
      outFilePath,
      withGeneratedHeader(withSourceTraceComments(result.code, ast, sourceName, { commentPrefix }), header),
      relSource,
    );

    if ((target === 'fastapi' || target === 'python') && result.artifacts && result.artifacts.length > 0) {
      for (const artifact of result.artifacts) {
        const artifactPath = resolve(outDir, artifact.path);
        mkdirSync(dirname(artifactPath), { recursive: true });
        const tracedContent = withSourceTraceComments(artifact.content, ast, sourceName, {
          entry: artifact.type === 'entry',
          commentPrefix,
        });
        writeGeneratedFileSync(artifactPath, withGeneratedHeader(tracedContent, header), relSource);
      }
    }

    // Flat Ink output still needs a runnable entrypoint. Emit a sibling
    // companion file that imports the generated component by filename, so
    // multi-file directory compiles do not collide on a shared index.tsx.
    if (target === 'ink' && result.artifacts && result.artifacts.length > 0) {
      const entryArtifact = result.artifacts.find((artifact) => artifact.type === 'entry');
      if (entryArtifact) {
        const entryFilePath = resolve(outDir, `${name}.entry.tsx`);
        const componentModule = `./${basename(outFileName, '.tsx')}.js`;
        const entryContent = entryArtifact.content.replace(/from '\.\/[^']+\.js';/, `from '${componentModule}';`);
        writeGeneratedFileSync(
          entryFilePath,
          withGeneratedHeader(
            withSourceTraceComments(entryContent, ast, sourceName, { entry: true, commentPrefix }),
            header,
          ),
          relSource,
        );
      }
    }

    // In flat mode (default), other targets skip artifact emission — single file output only.
    // Use structure != flat to emit per-screen component files + entry point.
  }
}

// ── Config loading ───────────────────────────────────────────────────────

function autoDetectTarget(): KernTarget | null {
  const pkgPath = resolve(process.cwd(), 'package.json');
  if (!existsSync(pkgPath)) return null;
  try {
    const pkg = JSON.parse(readFileSync(pkgPath, 'utf-8'));
    const allDeps = { ...pkg.dependencies, ...pkg.devDependencies };
    const keywords = Array.isArray(pkg.keywords)
      ? pkg.keywords.map((keyword: unknown) => String(keyword).toLowerCase())
      : [];
    const packageName = typeof pkg.name === 'string' ? pkg.name.toLowerCase() : '';
    const isInkCliPackage =
      Boolean(pkg.bin) ||
      keywords.some(
        (keyword: string) => keyword === 'ink' || keyword === 'cli' || keyword === 'terminal' || keyword === 'tui',
      ) ||
      /\b(cli|terminal|tui|ink)\b/.test(packageName);
    if (allDeps.next) return 'nextjs';
    if (allDeps.nuxt) return 'nuxt' as any;
    if (allDeps.ink && isInkCliPackage) return 'ink';
    if (allDeps.vue) return 'vue';
    if (allDeps['react-native']) return 'native';
    if (allDeps.fastapi) return 'fastapi';
    if (allDeps.flask || allDeps.django) {
      console.warn(
        `Warning: ${allDeps.flask ? 'Flask' : 'Django'} detected but no dedicated target — falling back to 'express' (generates TypeScript, not Python). Use --target=fastapi for Python output.`,
      );
      return 'express' as any;
    }
    if (allDeps.express || allDeps.fastify || allDeps.koa || allDeps.hono) return 'express';
    if (allDeps.tailwindcss && allDeps.react) return 'tailwind';
    if (allDeps.react) return 'web';
    return null;
  } catch {
    return null;
  }
}

export function loadConfig(): ResolvedKernConfig {
  const configPath = resolve(process.cwd(), 'kern.config.ts');
  if (existsSync(configPath)) {
    try {
      const jiti = createJiti(import.meta.url);
      const mod = jiti(configPath) as { default?: unknown };
      const userConfig = mod.default ?? mod;
      return resolveConfig(userConfig as Partial<KernConfig>);
    } catch (err) {
      console.error(`Warning: Failed to load kern.config.ts: ${(err as Error).message}`);
    }
  }

  const autoDetected = autoDetectTarget();
  return resolveConfig(autoDetected ? { target: autoDetected } : {});
}

/**
 * Register the framework-agnostic templates (arrow-fn, window-event) that kern
 * ships as built-ins. They expand identically under every target, so projects
 * don't need to run `kern init-templates` just to use a lambda export.
 */
function registerBuiltInTemplates(): void {
  for (const [filename, source] of Object.entries(COMMON_TEMPLATES)) {
    try {
      const ast = parseAndSurface(source);
      const nodes = ast.type === 'template' ? [ast] : (ast.children || []).filter((n) => n.type === 'template');
      for (const node of nodes) {
        registerTemplate(node, `<builtin:${filename}>`);
      }
    } catch (err) {
      console.error(`  Warning: Failed to load built-in template ${filename}: ${(err as Error).message}`);
    }
  }
}

export function loadTemplates(cfg: ResolvedKernConfig): void {
  clearTemplates();
  registerBuiltInTemplates();
  if (!cfg.templates || cfg.templates.length === 0) return;

  for (const templatePath of cfg.templates) {
    const resolved = resolve(process.cwd(), templatePath);
    if (!existsSync(resolved)) continue;

    const stat = statSync(resolved);
    const files: string[] = [];

    if (stat.isDirectory()) {
      for (const entry of readdirSync(resolved)) {
        if (entry.endsWith('.kern')) files.push(resolve(resolved, entry));
      }
    } else if (resolved.endsWith('.kern')) {
      files.push(resolved);
    }

    for (const file of files) {
      try {
        const source = readFileSync(file, 'utf-8');
        const ast = parseAndSurface(source, file);
        const nodes = ast.type === 'template' ? [ast] : (ast.children || []).filter((n) => n.type === 'template');
        for (const node of nodes) {
          registerTemplate(node, file);
        }
      } catch (err) {
        console.error(`  Warning: Failed to load template ${basename(file)}: ${(err as Error).message}`);
      }
    }
  }
}

// ── Shadow analysis (opt-in) ─────────────────────────────────────────────

/**
 * Run shadow semantic analysis on an already-parsed IR root. Wraps analyzeShadow()
 * and swallows errors from the optional `typescript` peer so a missing peer becomes
 * a single diagnostic rather than a crash.
 */
export async function runShadowAnalysis(root: IRNode, options?: ShadowAnalyzeOptions): Promise<ShadowDiagnostic[]> {
  try {
    return await analyzeShadow(root, options);
  } catch (err) {
    return [
      {
        rule: 'shadow-analysis-crashed',
        nodeType: root.type,
        message: `Shadow analysis failed: ${(err as Error).message}`,
      },
    ];
  }
}

/**
 * Print shadow diagnostics to the console using the same shape as parse diagnostics.
 * Returns the error / warning / info counts so callers can update their totals.
 */
export function surfaceShadowDiagnostics(
  diagnostics: readonly ShadowDiagnostic[],
  file: string,
): { errors: number; warnings: number } {
  if (diagnostics.length === 0) return { errors: 0, warnings: 0 };

  const tsErrors = diagnostics.filter((d) => d.rule === 'shadow-ts');
  const unsupported = diagnostics.filter((d) => d.rule === 'shadow-unsupported-context');
  const missingPeer = diagnostics.filter((d) => d.rule === 'shadow-typescript-missing');
  const crashed = diagnostics.filter((d) => d.rule === 'shadow-analysis-crashed');

  if (missingPeer.length > 0) {
    console.error(`\n${file}:`);
    for (const d of missingPeer) {
      console.error(`  [SHADOW] ${d.message}`);
    }
    return { errors: 0, warnings: missingPeer.length };
  }

  if (crashed.length > 0) {
    console.error(`\n${file}:`);
    for (const d of crashed) {
      console.error(`  [SHADOW] ${d.message}`);
    }
    return { errors: 0, warnings: crashed.length };
  }

  if (tsErrors.length > 0) {
    console.error(`\n${file}:`);
    for (const d of tsErrors) {
      const loc = d.line ? `${d.line}:${d.col ?? 1}` : '?';
      const code = d.tsCode ? ` TS${d.tsCode}` : '';
      console.error(`  [SHADOW${code}] ${loc}  ${d.message}`);
    }
  }

  if (unsupported.length > 0) {
    // Unsupported contexts are informational, not failures.
    for (const d of unsupported) {
      const loc = d.line ? `${d.line}:${d.col ?? 1}` : '?';
      console.error(`  [SHADOW-SKIP] ${loc}  ${d.message}`);
    }
  }

  return { errors: tsErrors.length, warnings: unsupported.length };
}
