import type {
  IRNode,
  KernConfig,
  KernTarget,
  ParseDiagnostic,
  ResolvedKernConfig,
  SchemaViolation,
  ShadowDiagnostic,
} from '@kernlang/core';
import {
  analyzeShadow,
  clearTemplates,
  collectCoverageGaps,
  detectTarget,
  expandTemplateNode,
  generateCoreNode,
  isCoreNode,
  isTemplateNode,
  KERN_VERSION,
  parseWithDiagnostics,
  registerTemplate,
  resolveConfig,
  validateSchema,
  validateSemantics,
  writeCoverageGaps,
} from '@kernlang/core';
import { transpileExpress } from '@kernlang/express';
import { transpileFastAPI } from '@kernlang/fastapi';
import { transpileMCP } from '@kernlang/mcp';
import { transpile } from '@kernlang/native';
import { generateReactNode, isReactNode, transpileNextjs, transpileTailwind, transpileWeb } from '@kernlang/react';
import { transpileInk, transpileTerminal } from '@kernlang/terminal';
import { transpileNuxt, transpileVue } from '@kernlang/vue';
import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'fs';
import { createJiti } from 'jiti';
import { basename, dirname, relative, resolve } from 'path';
import { transpileCliApp } from './transpiler-cli.js';

// ── Constants ────────────────────────────────────────────────────────────

export const GENERATED_HEADER = `// @generated by kern v${KERN_VERSION} — DO NOT EDIT. Source: `;

// ── Arg parsing helpers ──────────────────────────────────────────────────

/** Get value of --flag=value */
export function parseFlag(args: string[], flag: string): string | undefined {
  return args.find((a) => a.startsWith(`${flag}=`))?.split('=')[1];
}

/** Get value of --flag=value OR --flag <value> (next positional arg) */
export function parseFlagOrNext(args: string[], flag: string): string | undefined {
  const eqArg = args.find((a) => a.startsWith(`${flag}=`));
  if (eqArg) return eqArg.split('=')[1];
  const idx = args.indexOf(flag);
  return idx !== -1 && idx + 1 < args.length ? args[idx + 1] : undefined;
}

/** Check if any of the given flags are present */
export function hasFlag(args: string[], ...flags: string[]): boolean {
  return flags.some((f) => args.includes(f));
}

// ── Parse helpers ────────────────────────────────────────────────────────

export function surfaceParseDiagnostics(
  diagnostics: ParseDiagnostic[],
  file?: string,
): { errors: number; warnings: number } {
  if (diagnostics.length === 0) return { errors: 0, warnings: 0 };
  const prefix = file ? `${file}: ` : '';
  let errors = 0;
  let warnings = 0;
  for (const diagnostic of diagnostics) {
    const tag = diagnostic.severity === 'error' ? 'ERROR' : diagnostic.severity === 'warning' ? 'WARN' : 'INFO';
    console.error(`  ${prefix}[${tag}] ${diagnostic.code}: ${diagnostic.message}`);
    if (diagnostic.severity === 'error') errors++;
    else if (diagnostic.severity === 'warning') warnings++;
  }
  return { errors, warnings };
}

export function parseAndSurface(source: string, file?: string): IRNode {
  const result = parseWithDiagnostics(source);
  surfaceParseDiagnostics(result.diagnostics, file);
  return result.root;
}

// ── JSON Diagnostics (LLM consumption) ──────────────────────────────────

export interface FileDiagnosticsJSON {
  file: string;
  success: boolean;
  diagnostics: ParseDiagnostic[];
  schemaViolations: SchemaViolation[];
  shadowDiagnostics?: ShadowDiagnostic[];
}

/** Parse a .kern file and return structured diagnostics as JSON-serializable object. */
export function parseWithJSONDiagnostics(source: string, file: string): { root: IRNode; json: FileDiagnosticsJSON } {
  const result = parseWithDiagnostics(source);
  const schemaViolations = [
    ...validateSchema(result.root),
    ...validateSemantics(result.root).map((sv) => ({
      nodeType: sv.nodeType,
      message: `[${sv.rule}] ${sv.message}`,
      line: sv.line,
      col: sv.col,
    })),
  ];
  const hasErrors = result.diagnostics.some((d) => d.severity === 'error') || schemaViolations.length > 0;

  return {
    root: result.root,
    json: {
      file,
      success: !hasErrors,
      diagnostics: result.diagnostics,
      schemaViolations,
    },
  };
}

// ── Output extension helper ─────────────────────────────────────────────

/** Get the output file extension for a given target. Deduplicates the ternary chain. */
export function getOutputExtension(target: KernTarget): string {
  switch (target) {
    case 'fastapi':
      return '.py';
    case 'vue':
    case 'nuxt':
      return '.vue';
    case 'lib':
    case 'express':
    case 'cli':
    case 'terminal':
    case 'mcp':
      return '.ts';
    default:
      return '.tsx';
  }
}

// ── Export extraction ───────────────────────────────────────────────────

/** Extract exported symbol names from generated TypeScript lines, distinguishing type-only exports. */
export function extractExportsFromLines(lines: string[]): { name: string; typeOnly: boolean }[] {
  const exports: { name: string; typeOnly: boolean }[] = [];
  const re = /^export\s+(?:async\s+)?(?:function\*?|class|const|enum|abstract\s+class)\s+(\w+)/;
  const typeRe = /^export\s+(?:interface|type)\s+(\w+)/;
  for (const line of lines) {
    const m = line.match(re);
    if (m) {
      exports.push({ name: m[1], typeOnly: false });
      continue;
    }
    const tm = line.match(typeRe);
    if (tm) exports.push({ name: tm[1], typeOnly: true });
  }
  return exports;
}

// ── Barrel & Facade generation ──────────────────────────────────────────

export interface BarrelEntry {
  moduleName: string;
  exports: { name: string; typeOnly: boolean }[];
}

/** Scan output directory for .ts/.tsx files and build barrel entries from their exports. */
export function scanOutputForBarrelEntries(outDir: string): BarrelEntry[] {
  if (!existsSync(outDir)) return [];
  const entries: BarrelEntry[] = [];

  function scan(dir: string): void {
    for (const file of readdirSync(dir)) {
      const full = resolve(dir, file);
      if (statSync(full).isDirectory()) {
        scan(full);
        continue;
      }
      if (file === 'index.ts' || file === '_barrel.ts') continue;
      if (!file.endsWith('.ts') && !file.endsWith('.tsx')) continue;
      const content = readFileSync(full, 'utf-8');
      const exports = extractExportsFromLines(content.split('\n'));
      if (exports.length > 0) {
        // Use path relative to outDir as module name so barrel imports resolve
        const relPath = relative(outDir, full).replace(/\.tsx?$/, '');
        entries.push({ moduleName: relPath, exports });
      }
    }
  }

  scan(outDir);
  return entries;
}

/** Generate a barrel index file that re-exports from all compiled modules. */
export function generateBarrelFile(outDir: string, entries: BarrelEntry[]): void {
  if (entries.length === 0) return;
  const hasIndexKern = entries.some((e) => e.moduleName === 'index');
  const barrelName = hasIndexKern ? '_barrel.ts' : 'index.ts';
  const barrelLines = ['// @generated by kern — DO NOT EDIT.', ''];
  for (const entry of entries) {
    const valueExports = entry.exports.filter((e) => !e.typeOnly).map((e) => e.name);
    const typeExports = entry.exports.filter((e) => e.typeOnly).map((e) => e.name);
    if (valueExports.length > 0) {
      barrelLines.push(`export { ${valueExports.join(', ')} } from './${entry.moduleName}.js';`);
    }
    if (typeExports.length > 0) {
      barrelLines.push(`export type { ${typeExports.join(', ')} } from './${entry.moduleName}.js';`);
    }
  }
  barrelLines.push('');
  const barrelFile = resolve(outDir, barrelName);
  writeFileSync(barrelFile, barrelLines.join('\n'));
  const totalExports = entries.reduce((n, e) => n + e.exports.length, 0);
  console.log(`  barrel → ${barrelName} (${totalExports} exports)`);
}

/** Generate facade re-export files and an index.ts that re-exports from facades. */
export function generateFacadeFiles(
  outDir: string,
  facadesDirOverride: string | undefined,
  entries: BarrelEntry[],
): void {
  if (entries.length === 0) return;
  const facadesDirPath = resolve(facadesDirOverride || resolve(dirname(outDir), 'src'));
  mkdirSync(facadesDirPath, { recursive: true });
  const relToGenerated = relative(facadesDirPath, outDir);
  const facadeFiles: string[] = [];

  for (const entry of entries) {
    const facadeFile = resolve(facadesDirPath, `${entry.moduleName}.ts`);
    if (existsSync(facadeFile)) continue;
    // Create parent directories for nested module paths (e.g. routes/get-users)
    mkdirSync(dirname(facadeFile), { recursive: true });
    const relPath = `${relToGenerated}/${entry.moduleName}.js`;
    writeFileSync(facadeFile, `export * from '${relPath}';\n`);
    facadeFiles.push(entry.moduleName);
  }

  if (facadeFiles.length > 0) {
    console.log(`  facades → ${facadesDirPath} (${facadeFiles.length} files)`);
  }

  const parentDir = dirname(outDir);
  const relToFacades = relative(parentDir, facadesDirPath);
  const indexLines = ['// @generated by kern — DO NOT EDIT.', ''];
  for (const entry of entries) {
    indexLines.push(`export * from './${relToFacades}/${entry.moduleName}.js';`);
  }
  indexLines.push('');
  const indexFile = resolve(parentDir, 'index.ts');
  if (!existsSync(indexFile) || readFileSync(indexFile, 'utf-8').startsWith('// @generated by kern')) {
    writeFileSync(indexFile, indexLines.join('\n'));
    console.log(`  facades index → ${relative(process.cwd(), indexFile)}`);
  } else {
    console.log(`  facades index → skipped (${relative(process.cwd(), indexFile)} already exists)`);
  }
}

// ── File helpers ─────────────────────────────────────────────────────────

export function findNearestPackageJson(startDir: string): string | null {
  let dir = startDir;
  while (true) {
    const candidate = resolve(dir, 'package.json');
    if (existsSync(candidate)) return candidate;
    const parent = dirname(dir);
    if (parent === dir) return null;
    dir = parent;
  }
}

/** Load .kernignore patterns from the given directory (or nearest parent). */
function loadKernIgnore(startDir: string): string[] {
  let dir = startDir;
  while (true) {
    const candidate = resolve(dir, '.kernignore');
    if (existsSync(candidate)) {
      return readFileSync(candidate, 'utf-8')
        .split('\n')
        .map((l) => l.trim())
        .filter((l) => l && !l.startsWith('#'));
    }
    const parent = dirname(dir);
    if (parent === dir) return [];
    dir = parent;
  }
}

/** Escape regex special characters except * which is used as glob wildcard. */
function escapeRegexExceptStar(s: string): string {
  return s.replace(/[.+?^${}()|[\]\\]/g, '\\$&');
}

/** Check if a path matches any of the ignore patterns (simple glob-like matching). */
function isIgnored(filePath: string, baseDir: string, patterns: string[]): boolean {
  const rel = relative(baseDir, filePath);
  return patterns.some((pattern) => {
    if (pattern.endsWith('/')) return rel.startsWith(pattern) || rel.includes(`/${pattern}`);
    if (pattern.includes('*')) {
      // Escape regex chars, then convert * to .* and ** to match across directories
      const escaped = escapeRegexExceptStar(pattern)
        .replace(/\*\*/g, '@@GLOBSTAR@@')
        .replace(/\*/g, '[^/]*')
        .replace(/@@GLOBSTAR@@/g, '.*');
      const regex = new RegExp(`^${escaped}$`);
      return regex.test(rel) || regex.test(basename(filePath));
    }
    return rel === pattern || basename(filePath) === pattern;
  });
}

export function findKernFiles(dir: string, singleFile?: string): string[] {
  if (singleFile) return [resolve(dir, singleFile)];
  const ignorePatterns = loadKernIgnore(dir);
  const files: string[] = [];
  function walk(d: string): void {
    for (const entry of readdirSync(d)) {
      const full = resolve(d, entry);
      const s = statSync(full);
      if (s.isDirectory() && !entry.startsWith('.') && entry !== 'node_modules' && entry !== 'dist') {
        walk(full);
      } else if (entry.endsWith('.kern')) {
        if (ignorePatterns.length === 0 || !isIgnored(full, dir, ignorePatterns)) {
          files.push(full);
        }
      }
    }
  }
  walk(dir);
  return files;
}

export function collectTsFilesFlat(dirPath: string, recursive: boolean): string[] {
  const files: string[] = [];
  for (const entry of readdirSync(dirPath)) {
    const full = resolve(dirPath, entry);
    const s = statSync(full);
    if (s.isDirectory() && recursive && !entry.startsWith('.') && entry !== 'node_modules' && entry !== 'dist') {
      files.push(...collectTsFilesFlat(full, true));
    } else if (
      (entry.endsWith('.ts') || entry.endsWith('.tsx')) &&
      !entry.endsWith('.d.ts') &&
      !entry.endsWith('.test.ts')
    ) {
      files.push(full);
    } else if (entry.endsWith('.kern')) {
      files.push(full);
    } else if (entry.endsWith('.py') && !entry.startsWith('test_') && !entry.endsWith('_test.py')) {
      files.push(full);
    }
  }
  return files;
}

// ── Library passthrough transpiler ───────────────────────────────────────

/** Plain TypeScript output — no framework wrapper, no JSX, no scaffold. */
function transpileLib(ast: IRNode, _cfg: ResolvedKernConfig): import('@kernlang/core').TranspileResult {
  const lines: string[] = [];

  function processNode(node: IRNode): void {
    if (isCoreNode(node.type)) {
      lines.push(...generateCoreNode(node));
      lines.push('');
    } else if (isTemplateNode(node.type)) {
      lines.push(...expandTemplateNode(node));
      lines.push('');
    } else if (isReactNode(node.type)) {
      lines.push(...generateReactNode(node));
      lines.push('');
    }
  }

  processNode(ast);
  if (ast.children) {
    for (const child of ast.children) {
      processNode(child);
    }
  }

  const code = lines.join('\n');
  return { code, sourceMap: [], irTokenCount: 0, tsTokenCount: 0, tokenReduction: 0 };
}

// ── Transpile dispatch ───────────────────────────────────────────────────

export function transpileForTarget(ast: IRNode, cfg: ResolvedKernConfig) {
  const target = cfg.target === 'auto' ? detectTarget(ast) : cfg.target;
  return target === 'lib'
    ? transpileLib(ast, cfg)
    : target === 'native'
      ? transpile(ast, cfg)
      : target === 'web'
        ? transpileWeb(ast, cfg)
        : target === 'tailwind'
          ? transpileTailwind(ast, cfg)
          : target === 'mcp'
            ? transpileMCP(ast, cfg)
            : target === 'express'
              ? transpileExpress(ast, cfg)
              : target === 'fastapi'
                ? transpileFastAPI(ast, cfg)
                : target === 'cli'
                  ? transpileCliApp(ast, cfg)
                  : target === 'terminal'
                    ? transpileTerminal(ast, cfg)
                    : target === 'ink'
                      ? transpileInk(ast, cfg)
                      : target === 'vue'
                        ? transpileVue(ast, cfg)
                        : target === 'nuxt'
                          ? transpileNuxt(ast, cfg)
                          : transpileNextjs(ast, cfg);
}

// ── Transpile + write ────────────────────────────────────────────────────

export function transpileAndWrite(
  file: string,
  cfg: ResolvedKernConfig,
  args: string[],
  outDirOverride?: string,
  inputBase?: string,
): void {
  const source = readFileSync(file, 'utf-8');
  const ast = parseAndSurface(source, file);
  const ext = file.endsWith('.kern') ? '.kern' : '.ir';
  const name = basename(file, ext);
  const relSource = relative(process.cwd(), file);
  const header = `${GENERATED_HEADER + relSource}\n\n`;

  if (!args.includes('--no-gaps')) {
    const gaps = collectCoverageGaps(ast, file);
    if (gaps.length > 0) {
      writeCoverageGaps(gaps, resolve(process.cwd(), '.kern-gaps'));
    }
  }

  // Resolve auto target per-file from AST content
  const effectiveCfg = cfg.target === 'auto' ? { ...cfg, target: detectTarget(ast) } : cfg;
  const target = effectiveCfg.target;
  const result = transpileForTarget(ast, effectiveCfg);

  const relDir = inputBase ? relative(resolve(inputBase), dirname(file)) : '';
  const baseDir = outDirOverride ? resolve(resolve(outDirOverride), relDir) : dirname(file);
  const outDir = resolve(baseDir, cfg.output.outDir);
  mkdirSync(outDir, { recursive: true });

  if (result.artifacts && result.artifacts.length > 0 && cfg.structure !== 'flat') {
    for (const artifact of result.artifacts) {
      const artifactPath = resolve(outDir, artifact.path);
      mkdirSync(dirname(artifactPath), { recursive: true });
      writeFileSync(artifactPath, header + artifact.content);
    }
  } else {
    const outExt =
      target === 'fastapi'
        ? '.py'
        : target === 'vue' || target === 'nuxt'
          ? '.vue'
          : target === 'lib' || target === 'express' || target === 'cli' || target === 'terminal' || target === 'mcp'
            ? '.ts'
            : '.tsx';
    const resultWithFiles = result as { files?: Array<{ path: string; content: string }> };
    const outFileName =
      target === 'nextjs' && resultWithFiles.files && resultWithFiles.files.length > 0
        ? resultWithFiles.files[0].path
        : `${name}${outExt}`;
    const outFilePath = resolve(outDir, outFileName);
    mkdirSync(dirname(outFilePath), { recursive: true });
    writeFileSync(outFilePath, header + result.code);
    // In flat mode (default), skip artifact emission — single file output only.
    // Use structure: 'structured' to emit per-screen component files + entry point.
  }
}

// ── Config loading ───────────────────────────────────────────────────────

function autoDetectTarget(): KernTarget | null {
  const pkgPath = resolve(process.cwd(), 'package.json');
  if (!existsSync(pkgPath)) return null;
  try {
    const pkg = JSON.parse(readFileSync(pkgPath, 'utf-8'));
    const allDeps = { ...pkg.dependencies, ...pkg.devDependencies };
    if (allDeps.next) return 'nextjs';
    if (allDeps.nuxt) return 'nuxt' as any;
    if (allDeps.vue) return 'vue';
    if (allDeps['react-native']) return 'native';
    if (allDeps.fastapi) return 'fastapi';
    if (allDeps.flask || allDeps.django) {
      console.warn(
        `Warning: ${allDeps.flask ? 'Flask' : 'Django'} detected but no dedicated target — falling back to 'express' (generates TypeScript, not Python). Use --target=fastapi for Python output.`,
      );
      return 'express' as any;
    }
    if (allDeps.express || allDeps.fastify || allDeps.koa || allDeps.hono) return 'express';
    if (allDeps.tailwindcss && allDeps.react) return 'tailwind';
    if (allDeps.react) return 'web';
    return null;
  } catch {
    return null;
  }
}

export function loadConfig(): ResolvedKernConfig {
  const configPath = resolve(process.cwd(), 'kern.config.ts');
  if (existsSync(configPath)) {
    try {
      const jiti = createJiti(import.meta.url);
      const mod = jiti(configPath) as { default?: unknown };
      const userConfig = mod.default ?? mod;
      return resolveConfig(userConfig as Partial<KernConfig>);
    } catch (err) {
      console.error(`Warning: Failed to load kern.config.ts: ${(err as Error).message}`);
    }
  }

  const autoDetected = autoDetectTarget();
  return resolveConfig(autoDetected ? { target: autoDetected } : {});
}

export function loadTemplates(cfg: ResolvedKernConfig): void {
  clearTemplates();
  if (!cfg.templates || cfg.templates.length === 0) return;

  for (const templatePath of cfg.templates) {
    const resolved = resolve(process.cwd(), templatePath);
    if (!existsSync(resolved)) continue;

    const stat = statSync(resolved);
    const files: string[] = [];

    if (stat.isDirectory()) {
      for (const entry of readdirSync(resolved)) {
        if (entry.endsWith('.kern')) files.push(resolve(resolved, entry));
      }
    } else if (resolved.endsWith('.kern')) {
      files.push(resolved);
    }

    for (const file of files) {
      try {
        const source = readFileSync(file, 'utf-8');
        const ast = parseAndSurface(source, file);
        const nodes = ast.type === 'template' ? [ast] : (ast.children || []).filter((n) => n.type === 'template');
        for (const node of nodes) {
          registerTemplate(node, file);
        }
      } catch (err) {
        console.error(`  Warning: Failed to load template ${basename(file)}: ${(err as Error).message}`);
      }
    }
  }
}

// ── Shadow analysis (opt-in) ─────────────────────────────────────────────

/**
 * Run shadow semantic analysis on an already-parsed IR root. Wraps analyzeShadow()
 * and swallows errors from the optional `typescript` peer so a missing peer becomes
 * a single diagnostic rather than a crash.
 */
export async function runShadowAnalysis(root: IRNode): Promise<ShadowDiagnostic[]> {
  try {
    return await analyzeShadow(root);
  } catch (err) {
    return [
      {
        rule: 'shadow-analysis-crashed',
        nodeType: root.type,
        message: `Shadow analysis failed: ${(err as Error).message}`,
      },
    ];
  }
}

/**
 * Print shadow diagnostics to the console using the same shape as parse diagnostics.
 * Returns the error / warning / info counts so callers can update their totals.
 */
export function surfaceShadowDiagnostics(
  diagnostics: readonly ShadowDiagnostic[],
  file: string,
): { errors: number; warnings: number } {
  if (diagnostics.length === 0) return { errors: 0, warnings: 0 };

  const tsErrors = diagnostics.filter((d) => d.rule === 'shadow-ts');
  const unsupported = diagnostics.filter((d) => d.rule === 'shadow-unsupported-context');
  const missingPeer = diagnostics.filter((d) => d.rule === 'shadow-typescript-missing');
  const crashed = diagnostics.filter((d) => d.rule === 'shadow-analysis-crashed');

  if (missingPeer.length > 0) {
    console.error(`\n${file}:`);
    for (const d of missingPeer) {
      console.error(`  [SHADOW] ${d.message}`);
    }
    return { errors: 0, warnings: missingPeer.length };
  }

  if (crashed.length > 0) {
    console.error(`\n${file}:`);
    for (const d of crashed) {
      console.error(`  [SHADOW] ${d.message}`);
    }
    return { errors: 0, warnings: crashed.length };
  }

  if (tsErrors.length > 0) {
    console.error(`\n${file}:`);
    for (const d of tsErrors) {
      const loc = d.line ? `${d.line}:${d.col ?? 1}` : '?';
      const code = d.tsCode ? ` TS${d.tsCode}` : '';
      console.error(`  [SHADOW${code}] ${loc}  ${d.message}`);
    }
  }

  if (unsupported.length > 0) {
    // Unsupported contexts are informational, not failures.
    for (const d of unsupported) {
      const loc = d.line ? `${d.line}:${d.col ?? 1}` : '?';
      console.error(`  [SHADOW-SKIP] ${loc}  ${d.message}`);
    }
  }

  return { errors: tsErrors.length, warnings: unsupported.length };
}
