/**
 * File-role classifier — determines whether a source file is runtime code,
 * codegen, a rule definition, an example, a test, or a barrel re-export.
 *
 * Used to gate rules: e.g. server-hook only fires on 'runtime' files.
 */

import { SyntaxKind, type SourceFile } from 'ts-morph';
import type { FileRole } from './types.js';

/** Classify a source file's role based on AST evidence and path heuristics. */
export function classifyFileRole(sourceFile: SourceFile, filePath: string): FileRole {
  // 1. Test files
  if (/\.(test|spec)\.(tsx?|jsx?)$/.test(filePath) || /\/tests?\//.test(filePath) || /^test_/.test(filePath.split('/').pop() || '')) {
    return 'test';
  }

  // 2. Barrel / re-export only files
  if (isBarrelFile(sourceFile)) {
    return 'barrel';
  }

  // 3. Path-based heuristics (strong signals)
  const lower = filePath.toLowerCase();
  if (/\/(codegen|generated|__generated__|gen)\//i.test(lower) || /\/codegen-/.test(lower)) {
    return 'codegen';
  }
  if (/\/rules?\//i.test(lower) && /\/review\//.test(lower)) {
    return 'rule-definition';
  }
  if (/\/examples?\//i.test(lower) || /\/fixtures?\//i.test(lower) || /\/preview-/.test(lower.split('/').pop() || '')) {
    return 'example';
  }

  // 4. Content markers
  const fullText = sourceFile.getFullText();
  if (/\/\/\s*@generated/i.test(fullText) || /\/\/\s*Generated by/i.test(fullText) || /\/\/\s*Auto-generated/i.test(fullText)) {
    return 'codegen';
  }

  // 5. AST evidence: file produces string output containing JSX/hook patterns = codegen
  if (hasCodegenStringPatterns(sourceFile)) {
    return 'codegen';
  }

  // 6. Default
  return 'runtime';
}

/** A barrel file has only import/export declarations and no executable statements. */
function isBarrelFile(sourceFile: SourceFile): boolean {
  const statements = sourceFile.getStatements();
  if (statements.length === 0) return true;
  return statements.every(s => {
    const kind = s.getKind();
    return kind === SyntaxKind.ImportDeclaration
      || kind === SyntaxKind.ExportDeclaration
      || kind === SyntaxKind.ExportAssignment;
  });
}

/**
 * Detect codegen files that produce strings containing React hooks/JSX.
 * Checks template literals and string literals for hook call patterns.
 */
function hasCodegenStringPatterns(sourceFile: SourceFile): boolean {
  const hookPattern = /\buse(State|Effect|Ref|Callback|Memo|Reducer|Context)\s*[<(]/;

  // Check template literals containing hook patterns
  const templates = sourceFile.getDescendantsOfKind(SyntaxKind.TemplateExpression);
  const noSubTemplates = sourceFile.getDescendantsOfKind(SyntaxKind.NoSubstitutionTemplateLiteral);
  for (const t of [...templates, ...noSubTemplates]) {
    if (hookPattern.test(t.getText())) {
      return true;
    }
  }

  // Check string literals containing JSX-like patterns (codegen building HTML/JSX strings)
  const strings = sourceFile.getDescendantsOfKind(SyntaxKind.StringLiteral);
  let hookStringCount = 0;
  for (const s of strings) {
    if (hookPattern.test(s.getLiteralText())) {
      hookStringCount++;
      if (hookStringCount >= 3) return true; // 3+ hook mentions in strings = codegen
    }
  }

  return false;
}
