import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { mkdtempSync, readFileSync, readdirSync, rmSync, symlinkSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, relative, resolve, sep } from 'node:path';
import test from 'node:test';

import { STRUCTURAL_KIR_NODE_CATALOG } from '../../packages/core/dist/kir-structural/catalog.generated.js';
import { parseDocumentWithDiagnostics } from '../../packages/core/dist/parser.js';
import {
  loadPreBranchRuntimeConstitutionSource,
  loadPreEachRuntimeConstitutionSource,
  loadPreExpressionV1RuntimeConstitutionSource,
  loadPreLambdaRuntimeConstitutionSource,
  resolveRuntimeConstitutionSource,
  validateRuntimeCatalogConstitution,
} from './coverage-catalog.mjs';
import {
  digestM4145CompiledCoreJavaScript,
  digestPreM4135CompiledCoreJavaScript,
  reconstructM4145CompiledCoreJavaScriptPaths,
} from './coverage-dependencies.mjs';
import { freezeFunctionFacts, validateFunctionFacts } from './coverage-facts.mjs';
import {
  loadCoveragePolicy,
  measureCanonicalizerCoverage,
  selectCanonicalizerTranche,
  validateCoveragePolicy,
} from './coverage.mjs';
import { canonicalProfileRowsForFunction } from './coverage-profile.mjs';
import { writeCoverageSummary } from './coverage-summary-writer.mjs';
import { loadCanonicalizerPolicy } from './policy.mjs';

function digest(value) {
  return createHash('sha256').update(value).digest('hex');
}

function corpusPath(path) {
  return relative(process.cwd(), path).split(sep).join('/');
}

function repositoryCorpusFixture(prefix) {
  // Keep transient corpus data outside the implementation tree: other test
  // workers authenticate that tree recursively while these fixtures are live.
  return mkdtempSync(join(process.cwd(), `.kern-canonicalizer-${prefix}-`));
}

function compiledCorePaths() {
  const root = resolve(process.cwd(), 'packages/core/dist');
  const files = [];
  function visit(directory) {
    for (const entry of readdirSync(directory, { withFileTypes: true })) {
      const path = join(directory, entry.name);
      if (entry.isSymbolicLink()) throw new TypeError(`compiled core entry ${path} must not be a symlink`);
      if (entry.isDirectory()) visit(path);
      else if (entry.isFile() && entry.name.endsWith('.js')) files.push(path);
    }
  }
  visit(root);
  return files.map((path) => relative(root, path).split(sep).join('/')).sort();
}

function compiledCoreDigest({ omitted = new Set(), overrides = new Map() } = {}) {
  const root = resolve(process.cwd(), 'packages/core/dist');
  const hash = createHash('sha256');
  for (const name of compiledCorePaths()) {
    if (omitted.has(name)) continue;
    const bytes = overrides.get(name) ?? readFileSync(resolve(root, name));
    hash.update(`${name.length}:${name}:${bytes.length}:`);
    hash.update(bytes);
  }
  return hash.digest('hex');
}

function framedDigest(paths) {
  const hash = createHash('sha256');
  for (const path of [...paths].sort()) {
    const bytes = readFileSync(resolve(process.cwd(), path));
    hash.update(`${path.length}:${path}:${bytes.length}:`);
    hash.update(bytes);
  }
  return hash.digest('hex');
}

function coverageFact(overrides = {}) {
  return {
    excludedProperties: [],
    expressionKinds: [],
    expressionOccurrences: [],
    firstUnsupported: null,
    handlerChildProfiles: [['return']],
    id: 'examples/tool.kern#0:fixture',
    nodeKinds: [],
    nodeOccurrences: [],
    profileBlockers: [],
    profileRows: { nodes: 3, properties: 4, values: 5 },
    propertyKeys: [],
    propertyOccurrences: [],
    tool: 'tool',
    ...overrides,
  };
}

test('handwritten corpus admission rejects every repository generated header variant', () => {
  const directory = repositoryCorpusFixture('generated-header');
  try {
    for (const [index, source] of [
      '\ufeff \t# GENERATED FILE — do not hand-edit.\n',
      '\ufeff \t# @generated by kern v5.0.0 — DO NOT EDIT.\n',
    ].entries()) {
      const path = join(directory, `${index}.kern`);
      writeFileSync(path, source);
      const policy = loadCoveragePolicy();
      policy.corpus = [{
        digest: digest(source),
        path: corpusPath(path),
        sourceKind: 'handwritten',
        tool: 'generated-probe',
      }];
      assert.throws(() => validateCoveragePolicy(policy), /corpus member .* is generated/u);
    }
  } finally {
    rmSync(directory, { force: true, recursive: true });
  }
});

test('function facts bind unique sets exactly to occurrence evidence', () => {
  for (const fact of [
    coverageFact({ nodeKinds: ['fn'], nodeOccurrences: [] }),
    coverageFact({ expressionKinds: ['binary'], expressionOccurrences: [] }),
    coverageFact({ propertyKeys: ['fn.name'], propertyOccurrences: [] }),
  ]) {
    assert.throws(() => validateFunctionFacts([fact]), /occurrences must exactly derive kinds/u);
  }
});

test('function facts reject malformed property identities before selection', () => {
  for (const property of ['fn', '.name', 'fn.', 'fn.name.extra']) {
    const fact = coverageFact({
      propertyKeys: [property],
      propertyOccurrences: [property],
    });
    assert.throws(() => validateFunctionFacts([fact]), /property identity/u);
  }
});

test('function facts reject duplicate witness ids before ranking', () => {
  const fact = coverageFact();
  assert.throws(
    () => validateFunctionFacts([fact, structuredClone(fact)]),
    /duplicate function id/u,
  );
});

test('selection accepts only immutable facts created by the current measurement', () => {
  const policy = loadCoveragePolicy();
  const measured = measureCanonicalizerCoverage(policy);
  const clone = structuredClone(measured.functions);
  const driftedPolicy = structuredClone(policy);
  driftedPolicy.corpus[0].tool = 'invented-tool';
  assert.throws(() => measured.functions[0].excludedProperties.pop(), /read only|not extensible|Cannot delete/u);
  assert.throws(() => selectCanonicalizerTranche(policy, clone), /authenticated measurement/u);
  assert.throws(
    () => selectCanonicalizerTranche(driftedPolicy, measured.functions),
    /authenticated coverage policy/u,
  );
  assert.deepEqual(selectCanonicalizerTranche(policy, measured.functions), measured.selection);
});

test('historical measurement keeps selection bound to its authenticated canonicalizer policy', () => {
  const coveragePolicy = loadCoveragePolicy();
  const canonicalizerPolicy = loadCanonicalizerPolicy();
  canonicalizerPolicy.profileLimits = {
    maxNodeRows: 1,
    maxPropertyRows: 1,
    maxValueRows: 1,
  };
  const measured = measureCanonicalizerCoverage(coveragePolicy, canonicalizerPolicy);
  assert.equal(measured.selection.winner, null);
  assert.throws(
    () => selectCanonicalizerTranche(coveragePolicy, measured.functions),
    /authenticated canonicalizer policy/u,
  );
  assert.deepEqual(
    selectCanonicalizerTranche(coveragePolicy, measured.functions, canonicalizerPolicy),
    measured.selection,
  );
});

test('deep freezing descends through an already shallow-frozen fact container', () => {
  const functions = [coverageFact({ handlerChildProfiles: Object.freeze([['return']]) })];
  freezeFunctionFacts(functions);
  assert.throws(() => functions[0].handlerChildProfiles[0].push('throw'), /read only|not extensible/u);
});

test('coverage summary writes reject symlink destinations without touching targets', () => {
  const directory = mkdtempSync(join(tmpdir(), 'kern-coverage-summary-'));
  try {
    const target = join(directory, 'outside.json');
    const output = join(directory, 'coverage-summary.json');
    writeFileSync(target, 'outside\n');
    symlinkSync(target, output);
    assert.throws(() => writeCoverageSummary(output, { changed: true }), /regular file/u);
    assert.equal(readFileSync(target, 'utf8'), 'outside\n');
  } finally {
    rmSync(directory, { force: true, recursive: true });
  }
});

test('coverage summary checks require canonical bytes in a regular file', async () => {
  const { assertCoverageSummary } = await import('./coverage-summary-writer.mjs');
  assert.equal(typeof assertCoverageSummary, 'function');
  const directory = mkdtempSync(join(tmpdir(), 'kern-coverage-summary-check-'));
  try {
    const target = join(directory, 'target.json');
    const output = join(directory, 'coverage-summary.json');
    const summary = { format: 'fixture', value: 1 };
    writeCoverageSummary(output, summary);
    assert.doesNotThrow(() => assertCoverageSummary(output, summary));
    writeFileSync(output, `${JSON.stringify(summary)}\n`);
    assert.throws(() => assertCoverageSummary(output, summary), /canonical bytes/u);
    writeFileSync(target, `${JSON.stringify(summary, null, 2)}\n`);
    rmSync(output);
    symlinkSync(target, output);
    assert.throws(() => assertCoverageSummary(output, summary), /regular file/u);
  } finally {
    rmSync(directory, { force: true, recursive: true });
  }
});

test('profile-only rejection becomes the first unsupported fact', () => {
  const directory = repositoryCorpusFixture('profile-fact');
  try {
    const source = [
      'fn name=profileGap returns=string async=true',
      '  handler lang=kern',
      '    return value="\\"ok\\""',
      '',
    ].join('\n');
    const path = join(directory, 'profile-gap.kern');
    writeFileSync(path, source);
    const policy = loadCoveragePolicy();
    policy.corpus.push({
      digest: digest(source),
      path: corpusPath(path),
      sourceKind: 'handwritten',
      tool: 'profile-probe',
    });
    policy.corpus.sort((left, right) => left.path < right.path ? -1 : left.path > right.path ? 1 : 0);
    const measured = measureCanonicalizerCoverage(policy);
    const fact = measured.functions.find(({ id }) => id.endsWith(':profileGap'));
    assert.deepEqual(fact?.firstUnsupported, {
      category: 'profile',
      path: '$',
      value: 'fn.properties.async',
    });
  } finally {
    rmSync(directory, { force: true, recursive: true });
  }
});

test('profile-only firstUnsupported follows authored traversal order', () => {
  const directory = repositoryCorpusFixture('profile-order');
  try {
    const source = [
      'fn name=profileOrder returns=string stream=true async=true',
      '  handler lang=kern',
      '    return value="\\"ok\\""',
      '',
    ].join('\n');
    const path = join(directory, 'profile-order.kern');
    writeFileSync(path, source);
    const policy = loadCoveragePolicy();
    policy.corpus.push({
      digest: digest(source),
      path: corpusPath(path),
      sourceKind: 'handwritten',
      tool: 'profile-order-probe',
    });
    policy.corpus.sort((left, right) => left.path < right.path ? -1 : left.path > right.path ? 1 : 0);
    const measured = measureCanonicalizerCoverage(policy);
    const fact = measured.functions.find(({ id }) => id.endsWith(':profileOrder'));
    assert.deepEqual(fact?.firstUnsupported, {
      category: 'profile',
      path: '$',
      value: 'fn.properties.stream',
    });
  } finally {
    rmSync(directory, { force: true, recursive: true });
  }
});

test('firstUnsupported orders root profile blockers before descendant structural blockers', () => {
  const directory = repositoryCorpusFixture('combined-order');
  try {
    const source = [
      'fn name=combinedOrder returns=void async=true',
      '  handler lang=kern',
      '    if cond=true',
      '      return',
      '',
    ].join('\n');
    const path = join(directory, 'combined-order.kern');
    writeFileSync(path, source);
    const policy = loadCoveragePolicy();
    policy.corpus.push({
      digest: digest(source),
      path: corpusPath(path),
      sourceKind: 'handwritten',
      tool: 'combined-order-probe',
    });
    policy.corpus.sort((left, right) => left.path < right.path ? -1 : left.path > right.path ? 1 : 0);
    const measured = measureCanonicalizerCoverage(policy);
    const fact = measured.functions.find(({ id }) => id.endsWith(':combinedOrder'));
    assert.deepEqual(fact?.firstUnsupported, {
      category: 'profile',
      path: '$',
      value: 'fn.properties.async',
    });
  } finally {
    rmSync(directory, { force: true, recursive: true });
  }
});

test('the receipt binds the compiled core JavaScript used during measurement', () => {
  assert.equal(measureCanonicalizerCoverage().compiledCoreDigest, compiledCoreDigest());
});

test('current compiled core identity is sensitive to post-M4.145 runtime modules', () => {
  const current = compiledCoreDigest();
  const root = resolve(process.cwd(), 'packages/core/dist');
  for (const name of [
    'each-collection-reference.js',
    'kir-v1/canonical.js',
    'kir-v1/types.js',
    'kir-structural/each-collection-reference.js',
    'kir-structural/runtime-inflate.js',
    'runtime-envelope/kir-handler.js',
  ]) {
    const bytes = readFileSync(resolve(root, name));
    assert.notEqual(
      compiledCoreDigest({ overrides: new Map([[name, Buffer.concat([bytes, Buffer.from('\n')])]]) }),
      current,
      name,
    );
  }
});

test('historical compiled core identities authenticate exact M4.145 membership', () => {
  const currentPaths = compiledCorePaths();
  const historicalPaths = reconstructM4145CompiledCoreJavaScriptPaths(currentPaths);
  const omitted = new Set(currentPaths.filter((path) => !historicalPaths.includes(path)));
  assert.deepEqual([...omitted].sort(), [
    'each-collection-reference.js',
    'kir-structural/branch-path-value.js',
    'kir-structural/each-collection-reference.js',
    'kir-structural/runtime-inflate.js',
    'kir-v1/canonical.js',
    'kir-v1/types.js',
    'runtime-envelope/kir-handler.js',
  ]);
  assert.equal(
    digestM4145CompiledCoreJavaScript(),
    '29daa6ca4f8017ea214b72434c92b00b33a92f328a9f49798264f5c94e51f5b2',
  );
  assert.notEqual(digestM4145CompiledCoreJavaScript(), compiledCoreDigest({ omitted }));
  assert.equal(
    digestPreM4135CompiledCoreJavaScript(),
    '502bde3b1a95cbafa2039a0227d626aeceb605c0d9de5ebe24183ab9b37f10ec',
  );
  const sibling = 'runtime-envelope/source-handler.js';
  assert.ok(historicalPaths.includes(sibling));
  const siblingBytes = readFileSync(resolve(process.cwd(), 'packages/core/dist', sibling));
  assert.notEqual(
    compiledCoreDigest({
      omitted,
      overrides: new Map([[sibling, Buffer.concat([siblingBytes, Buffer.from('\n')])]]),
    }),
    digestM4145CompiledCoreJavaScript(),
  );
});

test('historical structural constitution chains exact pre-lambda, pre-each, pre-branch, and pre-expression bytes', () => {
  const preLambda = loadPreLambdaRuntimeConstitutionSource();
  assert.equal(
    digest(preLambda),
    'f9bef5fa63a370d084ff324cf1257b05d30170a5bf86cfa03393ec341b5d47ae',
  );
  assert.equal(digest(resolveRuntimeConstitutionSource(preLambda)), digest(preLambda));
  const preEach = loadPreEachRuntimeConstitutionSource();
  assert.equal(
    digest(preEach),
    '7e1072291f97583b2fc27dcd033732a76db104e99ebf12b09d2c5907057e408c',
  );
  assert.equal(digest(resolveRuntimeConstitutionSource(preEach)), digest(preEach));
  const preBranch = loadPreBranchRuntimeConstitutionSource();
  assert.equal(
    digest(preBranch),
    'fad83fc3f7a4b2b7b5f6b89bff2a47721cc06f1bba8a13a9b55be0bba8997ed7',
  );
  assert.equal(digest(resolveRuntimeConstitutionSource(preBranch)), digest(preBranch));
  assert.equal(
    digest(loadPreExpressionV1RuntimeConstitutionSource()),
    'fa3a0cddc280ff2d8dd9f09cf575953b5adbaaf6f8c716c05e06faf2d43cd6ea',
  );
  assert.throws(
    () => measureCanonicalizerCoverage(undefined, undefined, { constitutionSource: 'invented' }),
    /coverage catalog rejection/u,
  );
  assert.throws(
    () => measureCanonicalizerCoverage(undefined, undefined, {
      constitutionSource: Buffer.from('{"attacker":"controlled"}'),
    }),
    /coverage catalog rejection/u,
  );
});

test('M4.145 compiled core membership fails closed on inventory drift', () => {
  const currentPaths = compiledCorePaths();
  for (const paths of [
    [...currentPaths, 'runtime-envelope/future-handler.js'],
    currentPaths.filter((path) => path !== 'runtime-envelope/kir-handler.js'),
    [...currentPaths.slice(0, -1), currentPaths[0]],
    [...currentPaths.slice(0, -1), '../escaped.js'],
    [...currentPaths.slice(0, -1), 'runtime-envelope\\lookalike.js'],
  ]) {
    assert.throws(
      () => reconstructM4145CompiledCoreJavaScriptPaths(paths),
      /coverage dependency rejection/u,
    );
  }
});

test('the implementation digest path-frames every executed local dependency', () => {
  const directory = resolve(process.cwd(), 'scripts/kern-canonicalizer');
  const paths = readdirSync(directory, { withFileTypes: true })
    .filter((entry) => entry.isFile() && entry.name.endsWith('.mjs'))
    .map((entry) => `scripts/kern-canonicalizer/${entry.name}`);
  assert.equal(measureCanonicalizerCoverage().coverageImplementationDigest, framedDigest(paths));
});

test('the coverage entry authenticates dependencies before loading implementation modules', () => {
  const source = readFileSync(resolve(process.cwd(), 'scripts/kern-canonicalizer/coverage.mjs'), 'utf8');
  const authentication = source.indexOf('authenticateCoverageDependencies()');
  const implementationLoad = source.indexOf("await import('./coverage-implementation.mjs')");
  const verification = source.indexOf('verifyAuthenticatedCoverageDependencies(authenticated)');
  assert.ok(authentication >= 0 && implementationLoad > authentication && verification > implementationLoad);
});

test('catalog-required candidate properties and value grammar fail before completion rows exist', () => {
  const parsed = parseDocumentWithDiagnostics([
    'fn name=candidateContract returns=void',
    '  handler lang=kern',
    '    if cond=true',
    '      return',
  ].join('\n'));
  const missing = structuredClone(parsed.root.children[0]);
  delete missing.children[0].children[0].props.cond;
  assert.throws(
    () => canonicalProfileRowsForFunction(missing, loadCanonicalizerPolicy().kirLimits),
    (error) => error?.code === 'missing-property',
  );
  const malformed = structuredClone(parsed.root.children[0]);
  malformed.children[0].children[0].props.cond = { future: true };
  assert.throws(
    () => canonicalProfileRowsForFunction(malformed, loadCanonicalizerPolicy().kirLimits),
    /expected expression text or exact expression object/u,
  );
});

test('the executed runtime catalog must exactly match the hashed constitution', () => {
  const constitution = JSON.parse(readFileSync(
    new URL('../kir-structural/constitution.json', import.meta.url),
    'utf8',
  ));
  assert.doesNotThrow(() => validateRuntimeCatalogConstitution(constitution, STRUCTURAL_KIR_NODE_CATALOG));
  const mutated = structuredClone(constitution);
  mutated.nodes[0].reasonId = `${mutated.nodes[0].reasonId}-drift`;
  assert.throws(
    () => validateRuntimeCatalogConstitution(mutated, STRUCTURAL_KIR_NODE_CATALOG),
    /runtime catalog does not match the structural constitution/u,
  );
  for (const mutate of [
    (copy) => { copy.future = true; },
    (copy) => { copy.properties.push(structuredClone(copy.properties[0])); },
    (copy) => { copy.properties[0].nodeKind = 'not-a-constitution-node'; },
  ]) {
    const malformed = structuredClone(constitution);
    mutate(malformed);
    assert.throws(
      () => validateRuntimeCatalogConstitution(malformed, STRUCTURAL_KIR_NODE_CATALOG),
      /runtime catalog does not match the structural constitution/u,
    );
  }
});
